### ISSUE TITLE
Consul namer does not pick up on changes in consul anymore after consul was not reachable

### ISSUE THREAD

**Issue by bashofmann** [linkerd/linkerd#1230]
We are using linkerd with a consul namer. If there was a short connection error to consul for whatever reasons, linkerd seems to fail to re-connect to consul and will not receive any updates on where a service is available from consul anymore.

How to reproduce:

Tested with linkerd 0.9.0 and consul 0.8.1

Start a random web-service, in this case running on port 9012

Consul Config:

```
{
    "service": {
        "name": "my-service", 
        "port": 9012
    }, 
    "checks": [
        {
            "name": "my-service-health",
            "http": "http://localhost:9012/health",
            "service_id": "my-service",
            "interval": "5s"
        }
    ]
}
```

Start consul

```
consul agent -dev -advertise 127.0.0.1 -config-dir=/path/to/config
```

Linkerd config:

```
admin:
  port: 9991

namers:
- kind: io.l5d.consul
  host: localhost
  port: 8500
  useHealthCheck: true

routers:
- protocol: http
  dtab: |
    /svc  => /#/io.l5d.consul/dc1;
  label: consul
  servers:
  - port: 4140
    ip: 0.0.0.0

```

Start linkerd

```
linkerd ./linkerd.yaml
```

Do a request to my-service via linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
HTTP/1.1 200 OK
...
```

Now kill my-service. and do another request for this service to linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
```

The request returns a 502.

In the linkerd log you see the expected
```
0420 15:30:51.422 UTC THREAD19 TraceId:1f9aa75f534a156b: #/io.l5d.consul/dc1/my-service: name resolution is negative (local dtab: Dtab())
E 0420 15:30:52.245 UTC THREAD22 TraceId:c0f9420907d4ff25: service failure
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/my-service, Dtab.base=[/svc=>/#/io.l5d.consul/dc1], Dtab.local=[]. Remote Info: Not Available
```

Start my-service again.

Subsequent requests to my-service via linkerd will of course work again

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
HTTP/1.1 200 OK
...
```

Now stop consul and start it again

The linkerd log shows:

```
Failure(java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500. Remote Info: Upstream Address: /127.0.0.1:51163, Upstream Client Id: Not Available, Downstream Address: localhost/127.0.0.1:8500, Downstream Client Id: #/io.l5d.consul, Trace Id: 73204f8c5072fd90.73204f8c5072fd90<:73204f8c5072fd90, flags=0x10) with NoSources
Caused by: com.twitter.finagle.ChannelWriteException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500. Remote Info: Upstream Address: /127.0.0.1:51163, Upstream Client Id: Not Available, Downstream Address: localhost/127.0.0.1:8500, Downstream Client Id: #/io.l5d.consul, Trace Id: 73204f8c5072fd90.73204f8c5072fd90<:73204f8c5072fd90
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
    at java.lang.Thread.run(Thread.java:745)
```

Now kill my-service. and do another request for this service to linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
```

The request returns a 502 but linkerd still tries to connecto to port 9012 even though this is down in consul.

From the linkerd log

```
E 0420 15:11:47.832 UTC THREAD28 TraceId:0a943f473a987f04: service failure
com.twitter.finagle.ChannelWriteException: java.net.ConnectException: Connection refused: /127.0.0.1:9012. Remote Info: Upstream Address: /127.0.0.1:51799, Upstream Client Id: Not Available, Downstream Address: /127.0.0.1:9012, Downstream Client Id: #/io.l5d.consul/dc1/my-service, Trace Id: 0a943f473a987f04.0a943f473a987f04<:0a943f473a987f04
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9012
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
    at java.lang.Thread.run(Thread.java:745)
```

If I query consul for running nodes it returns nothing:

```
curl http://localhost:8500/v1/health/service/my-service\?passing\=true
[]
```

So after the short consul restart linkerd apparently did not connect back to consul and did not pick up of the change that there is no host available anymore for the requested service, but still tries to connecto to some (probably) cached information.
We observerd the same behavior if we add/remove hosts to consul.

**Comment by olix0r** [comment]
Thanks for the detailed report, @bashofmann.

Are you able to share linkerd's metrics when (1) linkerd is routing requests to my-service and (2) when consul is restarted and linkerd is still attempting to route requests to the downed instance?  I'm particularly curious about my-service's _loadbalancer_ stats (which show additions/removals/size/available) as well as metrics for the consul client itself.

Also, does linkerd stay in this state indefinitely (say, more than 5 minutes?)

**Comment by bashofmann** [comment]
In production we saw hosts that did not connect back to consul for days. I also just tested this with the above mentioned test setup and waited for 10 minutes and linkerd still tries to route the request to the downed instance.

I'll try to get you some metrics tomorrow.

**Comment by olix0r** [comment]
thanks! @Ashald you haven't seen anything like this, have you?

**Comment by esbie** [comment]
I'm able to reproduce this behavior using [the consul example from linkerd-examples ](https://github.com/linkerd/linkerd-examples/tree/master/consul)
repro steps:
```bash
docker-compose build && docker-compose up -d
docker-compose stop consul consul-registrator
docker-compose up -d consul consul-registrator
docker-compose stop service
# move the helloworld service from port 7777 to some other port
docker-compose up -d service
# confirm service is running on different port
curl http://localhost:8500/v1/catalog/service/helloworld
# try to call service
curl localhost:4140/helloworld
```

expected output:
`Hello!`

actual output:
`org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /172.27.0.3:7777. Remote Info: Upstream Address: /172.27.0.1:50422, Upstream Client Id: Not Available, Downstream Address: /172.27.0.3:7777, Downstream Client Id: #/io.l5d.consul/dc1/helloworld, Trace Id: 2ce882a90ff921cc.2ce882a90ff921cc<:2ce882a90ff921cc`

**Comment by bashofmann** [comment]
Unfortunately this issue is not fixed with 1.0.2

With the reproduction case I posted above, if my-service goes down I normally get this in the linkerd log:

```
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/my-service, Dtab.base=[/svc=>/#/io.l5d.consul/dc1], Dtab.local=[]. Remote Info: Not Available
```

But after I restart consul and then stop my-service again, the not running instance still stays in the list of up and running instances, and the log says instead

```
E 0515 11:05:48.964 UTC THREAD29 TraceId:47779e72188a85f0: service failure
Failure(Connection refused: /127.0.0.1:9012 at remote address: /127.0.0.1:9012. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /127.0.0.1:50808, Upstream Client Id: Not Available, Downstream Address: /127.0.0.1:9012, Downstream Client Id: #/io.l5d.consul/dc1/my-service, Trace Id: 47779e72188a85f0.47779e72188a85f0<:47779e72188a85f0
Caused by: com.twitter.finagle.ConnectionFailedException: Connection refused: /127.0.0.1:9012 at remote address: /127.0.0.1:9012. Remote Info: Not Available
	at com.twitter.finagle.netty3.ChannelConnector$$anon$2.operationComplete(Netty3Transporter.scala:79)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9012
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 9 more

```

**Comment by esbie** [comment]
Now reproduction with linkerd-examples is inconsistent but still possible. It takes 2 to 4 rounds of restarting consul before it shows up.

**Comment by esbie** [comment]
@bashofmann metrics from your instance would be helpful in debugging, thanks!

**Comment by esbie** [comment]
For the record, v1.0.2 recovers 5 minutes after consul restart (whereas previously, recovery never occurred)
