### ISSUE TITLE
Linkerd 1.0.2 java.lang.IllegalArgumentException: hostname can't be null exception when loadBalancer has hostname instead of ip

### ISSUE THREAD

**Issue by lkysow** [linkerd/linkerd#1322]
Kubernetes Version 1.6.2
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

Linkerd Version 1.0.2

Exception
```
E 0517 02:06:07.781 UTC THREAD32: k8s failed to list endpoints
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$7(ServiceNamer.scala:207)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$6(ServiceNamer.scala:205)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$6$adapted(ServiceNamer.scala:204)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$5(ServiceNamer.scala:204)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$5$adapted(ServiceNamer.scala:203)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$4(ServiceNamer.scala:203)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$4$adapted(ServiceNamer.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$3(ServiceNamer.scala:202)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$3$adapted(ServiceNamer.scala:201)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$2(ServiceNamer.scala:201)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$2$adapted(ServiceNamer.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$1(ServiceNamer.scala:200)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$1$adapted(ServiceNamer.scala:199)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.io$buoyant$k8s$ServiceCache$$extractPorts(ServiceNamer.scala:199)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$3(ServiceNamer.scala:139)
	at scala.Option.map(Option.scala:146)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$2(ServiceNamer.scala:138)
	at scala.Option.flatMap(Option.scala:171)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$1(ServiceNamer.scala:137)
```

Severity: Linkerd can't load any Kubernetes services so routing doesn't work

Occurs due to this line of code: https://github.com/linkerd/linkerd/blob/master/k8s/src/main/scala/io/buoyant/k8s/ServiceNamer.scala#L207 which assumes that if there is an `ingress` object, it will have an `ip` key, however it's possible this has a `hostname` key instead. See spec: https://kubernetes.io/docs/resources-reference/v1.6/#loadbalanceringress-v1-core.

Indeed for our grafana pod it has an ELB so the json looks like
```
            "status": {
                "loadBalancer": {
                    "ingress": [
                        {
                            "hostname": "abc123.us-east-1.elb.amazonaws.com"
                        }
                    ]
                }
            }
```

**Comment by lkysow** [comment]
I think these `v1.scala` and `v1beta1.scala` (https://github.com/linkerd/linkerd/blob/07f34ba01d894319c661922eb003dce1db787e77/k8s/src/main/scala/io/buoyant/k8s/v1beta1.scala#L115) need to be modified:
```diff
  case class LoadBalancerIngress(
-    ip: String
+    ip: Option[String] = None,
+    hostname: Option[String] = None
  )
```

And then `ServiceNamer` https://github.com/linkerd/linkerd/blob/master/k8s/src/main/scala/io/buoyant/k8s/ServiceNamer.scala#L203 can be modified

```diff
    for {
      meta <- service.metadata.toSeq
      name <- meta.name.toSeq
      status <- service.status.toSeq
      lb <- status.loadBalancer.toSeq
      ingress <- lb.ingress.toSeq.flatten
+     hostname <- ingress.hostname.orElse(ingress.ip)
      spec <- service.spec.toSeq
      port <- spec.ports
    } {
-    ports += port.name -> Address(new InetSocketAddress(ingress.ip, port.port))
+    ports += port.name -> Address(new InetSocketAddress(hostname, port.port))
      portMap += (port.targetPort match {
        case Some(targetPort) => port.port -> targetPort
        case None => port.port -> port.port
      })
    }
```

**Comment by adleong** [comment]
@lkysow: thanks for tracking this down!  that fix looks correct to me.  would you like to submit a pull request?  otherwise I can put one together based on your diff.

**Comment by lkysow** [comment]
@adleong done (#1323) wasn't sure how best to modify the tests. Feel free to work off that PR or just take the changes into your own.

**Comment by marccardinal** [comment]
When do you think this will be released? I ran into this problem when I upgraded k8s to 1.6 this morning.
