### ISSUE TITLE
linkerd caching initial zookeeper ip address(es) when hostname is used

### ISSUE THREAD

**Issue by rbaumgartner** [linkerd/linkerd#1340]
Linkerd appears to be caching the IP address associated with the zookeeper server or observer hostname that was initially resolved.  After updating the related zookeeper DNS record, linkerd continues to attempt to access zookeeper at the old/expired IP address.  TTLs were set very low in preparation of the zookeeper server/observer replacements and the instance hosting the linkerd service is aware of the DNS record update and resolves the new/proper IP address.  Other zookeeper dependent services on the same instances were also aware of the change and were able to connect to zookeeper at new ip addresses.  Restarting linkerd resolves the issue until another change is made the the associated DNS record.

VERSION INFO
linkerd 1.0.2
Finagle version 6.44.0
sidecar config (any zk dependent config should do)

ISSUE REPLICATION
1. update hosts file `127.0.0.1  zk.local`
2. install linkerd and update linkerd config to point to `zk.local` (do not run zookeeper on this server)
3. start linkerd and notice connection refuse messages (see sample log entry below)
4. update hosts file entry from `127.0.0.1  zk.local` to `<zk_server_ip>  zk.local`
5. notice that linkerd continues to attempt to access zookeeper server at 127.0.0.1

SAMPLE LINKERD LOG ENTRY (hostname, ip address, session id, and port removed)
```
WARN 0522 19:41:51.753 UTC main-SendThread(<hostname>:<port>): Session <session_id> for server <hostname>/<expired_ip>:<port>, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:356)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1192)
```

**Comment by wmorgan** [comment]
Thanks for the report, @rbaumgartner. We'll take a look!

**Comment by adleong** [comment]
Thanks @rbaumgartner!

Unfortunately this is a behavior of Java's InetSocketAddress that the hostname is resolved once when the InetSocketAddress is created and then never again.  This means that it will never pickup DNS changes.  (This is one of many reasons why we believe that DNS is not well suited for use as service discovery)

**Comment by wmorgan** [comment]
@rbaumgartner how often do you make this change? And OOC, are any of the other Zookeeper-dependent services that were able to make the change JVM applications?
