### ISSUE TITLE
Connection leak in kubernetes pod of DaemonSet deployment

### ISSUE THREAD

**Issue by turchanov** [linkerd/linkerd#1344]
I am trying to deploy https://blog.buoyant.io/2016/10/04/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics/. The problem is triggered by another problem (#1347) where linkerd cannot retrieve endpoint list via kubelet proxy (see stacktrace below). Due to this linkerd process keeps allocating connections to 127.0.0.1:8001 (kubelet proxy) and not closes them. After a while process runs out ephemeral ports for socket pairs.

netstat -nt shows growing number of connections to 127.0.0.1:8001

```
I 0525 02:30:08.315 UTC THREAD10: k8s initializing default
E 0525 02:30:08.330 UTC THREAD26: k8s failed to list endpoints
io.buoyant.k8s.Api$UnexpectedResponse
         at io.buoyant.k8s.Api$.parse(Api.scala:67)
         at io.buoyant.k8s.ListResource.$anonfun$get$2(resources.scala:136)
         at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1089)
         at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
         at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
         at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
         at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
         at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
         at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
         at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
         at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
         at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
         at com.twitter.util.Promise.runq(Promise.scala:406)
         at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
         at com.twitter.util.Promise.update(Promise.scala:775)
         at com.twitter.util.Promise.setValue(Promise.scala:751)
         at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
         at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:56)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
         at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
         at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
         at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
         at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
         at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
         at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
         at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
         at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
         at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
         at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
         at java.lang.Thread.run(Thread.java:745)
```

**Comment by adleong** [comment]
Thanks for the report!

**Comment by adleong** [comment]
I am able to reproduce this in minikube with [this config](https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/linkerd.yml) by turning on RBAC so that requests to the kubectl proxy fail.

This may be due to the kubernetes namer's infinite retry filter not discarding failed responses.

**Comment by turchanov** [comment]
Yes, indeed, the issue is triggered by RBAC. I posted a bug report for that.
