### ISSUE TITLE
switch base docker image to openjdk:8-jre-alpine

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd#1369]
Replace `library/java:openjdk-8-jre` with `library/openjdk:8-jre-alpine`.

Depends on #1368.

**Comment by siggy** [comment]
encountered error in integration tests, investigating:
```
WARN 0817 21:31:09.167 GMT finagle/netty4-8: Failed to initialize a channel. Closing: [id: 0x5c0a2612]
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:317)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:272)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:770)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientEngineFactory.apply(Netty4ClientEngineFactory.scala:66)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1(Netty4ClientSslHandler.scala:114)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1$adapted(Netty4ClientSslHandler.scala:111)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.initChannel(Netty4ClientSslHandler.scala:111)
```

**Comment by siggy** [comment]
abandoning this change, as alpine does not provide the libs we need, more details at https://github.com/linkerd/linkerd/issues/1581
