### ISSUE TITLE
can't build from source with ./sbt and the https://github.com/linkerd/linkerd/archive/1.0.2.tar.gz

### ISSUE THREAD

**Issue by ldemailly** [linkerd/linkerd#1371]
can't build from source with ./sbt and the https://github.com/linkerd/linkerd/archive/1.0.2.tar.gz:
downloaded the latest source release, extracted and:

```
$ ./sbt 
[info] Loading project definition from .../linkerd-1.0.2/project
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[...]
fatal: Not a git repository (or any of the parent directories): .git
java.lang.RuntimeException: Nonzero exit value: 128
        at scala.sys.package$.error(package.scala:27)
        at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
        at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
        at Base$Git$.<init>(Base.scala:39)
        at Base.Git$lzycompute(Base.scala:37)
        at Base.Git(Base.scala:37)
        at Base$$anonfun$8.apply(Base.scala:48)
        at Base$$anonfun$8.apply(Base.scala:48)
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit value: 128
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

from the error, I'm guessing I should git clone instead of using the source tgz but it should probably work without git no ?

**Comment by olix0r** [comment]
You're correct.  Our sbt setup currently runs some git commands to figure out if it's at a stable release tag.  This should probably be changed to handle non-git builds (or our archive should include some sort of .git).

**Comment by ldemailly** [comment]
thanks ! it does work after git clone + git checkout 0.1.2
