### ISSUE TITLE
java.lang.ClassCastException when targetPort is set as the port name string instead of the port number

### ISSUE THREAD

**Issue by kumudt** [linkerd/linkerd#1385]
Linkerd is getting flooded with these exceptions when targetPort of any service in the cluster is set to the port name defined in the container spec instead of setting the numeric port.
```
I 0613 18:27:26.741 UTC THREAD10: k8s initializing linkerd
E 0613 18:27:26.853 UTC THREAD25: k8s failed to list endpoints
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$6(ServiceNamer.scala:212)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$5(ServiceNamer.scala:204)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$5$adapted(ServiceNamer.scala:203)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$4(ServiceNamer.scala:203)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$4$adapted(ServiceNamer.scala:202)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$3(ServiceNamer.scala:202)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$3$adapted(ServiceNamer.scala:201)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$2(ServiceNamer.scala:201)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$2$adapted(ServiceNamer.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$1(ServiceNamer.scala:200)
	at io.buoyant.k8s.ServiceCache$.$anonfun$extractPorts$1$adapted(ServiceNamer.scala:199)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at io.buoyant.k8s.ServiceCache$.io$buoyant$k8s$ServiceCache$$extractPorts(ServiceNamer.scala:199)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$3(ServiceNamer.scala:139)
	at scala.Option.map(Option.scala:146)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$2(ServiceNamer.scala:138)
	at scala.Option.flatMap(Option.scala:171)
	at io.buoyant.k8s.ServiceCache.$anonfun$initialize$1(ServiceNamer.scala:137)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.immutable.List.flatMap(List.scala:341)
	at io.buoyant.k8s.ServiceCache.initialize(ServiceNamer.scala:136)
	at io.buoyant.k8s.ServiceCache.initialize(ServiceNamer.scala:69)
	at io.buoyant.k8s.Ns.$anonfun$watch$2(Ns.scala:82)
	at com.twitter.util.Future.$anonfun$map$2(Future.scala:1145)
	at com.twitter.util.Try$.apply(Try.scala:15)
	at com.twitter.util.Future$.apply(Future.scala:163)
	at com.twitter.util.Future.$anonfun$map$1(Future.scala:1145)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:406)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
	at com.twitter.util.Promise.update(Promise.scala:775)
	at com.twitter.util.Promise.setValue(Promise.scala:751)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:56)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:745)
```
These high frequency exceptions are crashing the log collection agents. It would be great if Linkerd recognizes and evaluates the targetPort name.

**Comment by kumudt** [comment]
@adleong Thanks for helping me Identify the issue.
