### ISSUE TITLE
sbt compile for Win32 fails on protoc

### ISSUE THREAD

**Issue by rake36** [linkerd/linkerd#1397]
Same issue as #1066 . Even with new protoc script that tries to download protoc executable, this still fails on Windows.

To get around issue, I renamed .protoc and protoc to temporarily disable and then copied in protoc.exe.

I get the same error as in issue #1066 

`[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\grpc\interop\src\main\protobuf\empty.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\grpc\interop\src\main\protobuf\messages.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\grpc\interop\src\main\protobuf\test.proto
[error] --io.buoyant.grpc_out: protoc-gen-io.buoyant.grpc: The system cannot find the file specified.
[error]
[error]
[info] Compiling 2 protobuf files to C:\Users\drakestraw\development\src\linkerd\grpc\eg\target\scala-2.12\src_managed\m
ain\compiled_protobuf
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\grpc\eg\src\main\protobuf\base.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\grpc\eg\src\main\protobuf\eg.proto
[error] --io.buoyant.grpc_out: protoc-gen-io.buoyant.grpc: The system cannot find the file specified.
[error]
[error]
[info] Compiling 1 protobuf files to C:\Users\drakestraw\development\src\linkerd\linkerd\core\target\scala-2.12\src_mana
ged\main\compiled_protobuf
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\linkerd\core\src\main\protobuf\usage.proto
[error] --io.buoyant.grpc_out: protoc-gen-io.buoyant.grpc: The system cannot find the file specified.
[error]
[error]
[info] Compiling 5 protobuf files to C:\Users\drakestraw\development\src\linkerd\mesh\core\target\scala-2.12\src_managed
\main\compiled_protobuf
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\mesh\core\src\main\protobuf\resolver.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\mesh\core\src\main\protobuf\codec.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\mesh\core\src\main\protobuf\delegator.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\mesh\core\src\main\protobuf\dtab.proto
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\mesh\core\src\main\protobuf\interpreter.proto
[error] --io.buoyant.grpc_out: protoc-gen-io.buoyant.grpc: The system cannot find the file specified.
[error]
[error]
[info] Updating {file:/C:/Users/drakestraw/development/src/linkerd/}linkerd-examples...`

**Comment by rake36** [comment]
Output from showing the last exception:

`[info] Done updating.
[trace] Stack trace suppressed: run last linkerd-core/protobuf:protobufGenerate for the full output.
[trace] Stack trace suppressed: run last grpc-interop/protobuf:protobufGenerate for the full output.
[trace] Stack trace suppressed: run last grpc-eg/protobuf:protobufGenerate for the full output.
[trace] Stack trace suppressed: run last mesh-core/protobuf:protobufGenerate for the full output.
[error] (linkerd-core/protobuf:protobufGenerate) protoc returned exit code: 1
[error] (grpc-interop/protobuf:protobufGenerate) protoc returned exit code: 1
[error] (grpc-eg/protobuf:protobufGenerate) protoc returned exit code: 1
[error] (mesh-core/protobuf:protobufGenerate) protoc returned exit code: 1
[error] Total time: 290 s, completed Jun 15, 2017 4:34:54 PM
> last linkerd-core/protobuf:protobufGenerate
[info] Compiling 1 protobuf files to C:\Users\drakestraw\development\src\linkerd\linkerd\core\target\scala-2.12\src_mana
ged\main\compiled_protobuf
[debug] protoc options:
[debug]         --io.buoyant.grpc_out=plugins=grpc:C:\Users\drakestraw\development\src\linkerd\linkerd\core\target\scala
-2.12\src_managed\main\compiled_protobuf
[info] Compiling schema C:\Users\drakestraw\development\src\linkerd\linkerd\core\src\main\protobuf\usage.proto
java.lang.RuntimeException: protoc returned exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbtprotobuf.ProtobufPlugin$.sbtprotobuf$ProtobufPlugin$$compile(ProtobufPlugin.scala:88)
        at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtobufPlugin.scala:115)
        at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$5.apply(ProtobufPlugin.scala:114)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtobufPlugin.scala:117)
        at sbtprotobuf.ProtobufPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtobufPlugin.scala:112)
        at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
        at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (linkerd-core/protobuf:protobufGenerate) protoc returned exit code: 1`

**Comment by wmorgan** [comment]
Thanks, @rake36! We'll take a look!

**Comment by rake36** [comment]
Thanks. If you need me to try anything, just let me know. In case it matters, running on Windows 7 x64. Can recreate whether running inside git bash or Windows command prompt.

**Comment by adleong** [comment]
We don't officially support windows but would likely accept pull requests for this.

**Comment by rake36** [comment]
Ok, thanks. We've come up with a work-around to run linkerd on windows.

If you run the following, it works fine.

`java -cp linkerd-1.1.0-exec io.buoyant.linkerd.Main config/linkerd.yaml`

**Comment by wmorgan** [comment]
@rake36 that's great! Sorry for the pain here, none of us are developing on Windows at the moment so this sort of friction occasionally happens. Glad we found a workaround.
