### ISSUE TITLE
Linkerd Docker image fails to use BoringSSL on Linux

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1581]
As initially reported [on Discourse](https://discourse.linkerd.io/t/linkerd-h2-router-rejects-requests-from-go-client/216/3?u=eliza), proxying H2 TLS connections with the the `linkerd:latest` Docker image fails with the message "JDK provider does not support NPN_AND_ALPN protocol". This message appears to indicate that BoringSSL is not being used and Linkerd is falling back to the JDK-provided SSL implementation. 

Curiously, this issue only seems to exist when the Docker image is run from a Linux host – I originally [attempted to reproduce the issue on macOS](https://discourse.linkerd.io/t/linkerd-h2-router-rejects-requests-from-go-client/216/6?u=eliza) and everything worked fine. After trying the same configuration on Linux in GCE, I was able to reproduce the issue.

**Comment by hawkw** [comment]
### Notes to reproduce:
The VM instance in which I reproduced the bug is still available in the `buoyant-hosted` GCE project, named `linux-test`; the Linkerd configs and SSL certs I used for the repro live in `/home/eliza/test` on that machine.

I launched Linkerd with
 ```shell
$ docker run --net="host" -v /home/eliza/test:/certs buoyantio/linkerd:latest /certs/linkerd.yml
```
and `nghttpd` with
```shell
$ nghttpd 8888 linkerd-tls-e2e-key.pem linkerd-tls-e2e-cert.pem -v 
```
and then hit Linkerd with a request from `nghttp`:
```shell
$ nghttp https://localhost:4240/ --cert=linkerd-tls-e2e-cert.pem --key=linkerd-tls-e2e-key.pem -v 
```

**Comment by adleong** [comment]
Would be interested to see if this still happens with this base image: https://github.com/linkerd/linkerd/issues/1369

**Comment by siggy** [comment]
Confirmed this is happening with alpine: https://github.com/linkerd/linkerd/pull/1596#issuecomment-323204885

**Comment by hawkw** [comment]
Ugh. Thanks for looking into that, @siggy.

**Comment by siggy** [comment]
The failure with alpine appears to be slightly different than the failure reported here. Both eventually fail with `java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol`:
- `1.1.3` fails to create a `JdkSslClientContext`, but gets much farther.
- `alpine` fails to create a `JdkSslServerContext`.

## 1.1.3

```bash
$ nghttp https://localhost:4240/ --cert=linkerd-tls-e2e-cert.pem --key=linkerd-tls-e2e-key.pem -v
[  0.004] Connected
The negotiated protocol: h2
[  0.366] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.366] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.366] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.366] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.367] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.367] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.367] send HEADERS frame <length=38, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: https
          :authority: localhost:4240
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.7.1
[  0.797] recv SETTINGS frame <length=0, flags=0x00, stream_id=0>
          (niv=0)
[  0.797] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.797] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  1.303] recv RST_STREAM frame <length=4, flags=0x00, stream_id=13>
          (error_code=REFUSED_STREAM(0x07))
[  1.303] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])
Some requests were not processed. total=1, processed=0
```

```bash
$ docker run --net="host" -v /home/eliza/test:/certs buoyantio/linkerd:1.1.3 /certs/linkerd.yml
...
WARN 0818 18:19:29.599 UTC finagle/netty4-2: Failed to initialize a channel. Closing: [id: 0xfba2a7ee]
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:317)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:272)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:770)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientEngineFactory.apply(Netty4ClientEngineFactory.scala:66)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1(Netty4ClientSslHandler.scala:114)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1$adapted(Netty4ClientSslHandler.scala:111)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.initChannel(Netty4ClientSslHandler.scala:111)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:178)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:143)
	at com.twitter.finagle.netty4.channel.AbstractNetty4ClientChannelInitializer.initChannel(AbstractNetty4ClientChannelInitializer.scala:77)
	at com.twitter.finagle.netty4.channel.RawNetty4ClientChannelInitializer.initChannel(RawNetty4ClientChannelInitializer.scala:18)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
```

## Alpine

```bash
$ nghttp https://localhost:4240/ --cert=linkerd-tls-e2e-cert.pem --key=linkerd-tls-e2e-key.pem -v
[  0.004] Connected
Some requests were not processed. total=1, processed=0
```

```bash
$ docker run --net="host" -v /home/eliza/test:/certs buoyantio/linkerd:openjdk-alpine2 /certs/linkerd.yml
...
WARN 0818 18:10:12.335 GMT finagle/netty4-1: Failed to initialize a channel. Closing: [id: 0x2ab1e070, L:/127.0.0.1:4240 - R:/127.0.0.1:52074]
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:317)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:239)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:415)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerEngineFactory.apply(Netty4ServerEngineFactory.scala:51)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.$anonfun$initChannel$1(Netty4ServerSslHandler.scala:75)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.$anonfun$initChannel$1$adapted(Netty4ServerSslHandler.scala:72)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslHandler.initChannel(Netty4ServerSslHandler.scala:72)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:178)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:143)
	at com.twitter.finagle.netty4.channel.Netty4RawServerChannelInitializer.initChannel(Netty4RawServerChannelInitializer.scala:54)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
	at com.twitter.finagle.netty4.Netty4Listener$$anon$1$$anon$2.initChannel(Netty4Listener.scala:158)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
^CI 0818 18:10:30.189 UTC THREAD19: Received SIGINT. Shutting down ...
```

**Comment by siggy** [comment]
With `log4j.rootLogger=ALL, stderr` on alpine, we see:
```
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
...
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_646657845700759905707.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty-tcnative-linux-x86_646657845700759905707.so)
...
DEBUG 0818 19:51:43.378 GMT main: Unable to load the library 'netty-tcnative-linux-x86_64-fedora', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty-tcnative-linux-x86_64-fedora in java.library.path
...
DEBUG 0818 19:51:43.380 GMT main: Unable to load the library 'netty-tcnative-linux-x86_64-fedora', trying next name...
java.lang.UnsatisfiedLinkError: no netty-tcnative-linux-x86_64-fedora in java.library.path
...
DEBUG 0818 19:51:43.383 GMT main: Unable to load the library 'netty-tcnative', trying next name...
java.lang.UnsatisfiedLinkError: no netty-tcnative in java.library.path
...
DEBUG 0818 19:51:43.387 GMT main: Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See http://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]
```

full startup output: https://gist.github.com/siggy/964494497529954c99832626d9eff899

**Comment by siggy** [comment]
a little more digging, it appears any linkerd h2 client configured with `clientAuth` exhibits this behavior.

**Comment by siggy** [comment]
reproduced on osx:

### linkerd

```bash
./sbt linkerd-examples/client-auth:run -log.level=DEBUG -com.twitter.finagle.tracing.debugTrace=true
```

### strest-server

```bash
strest-server -address=:1234
```

### strest-client

```bash
strest-client -address localhost:4143
```

### linkerd config

```yaml
routers:
- protocol: h2
  experimental: true
  label: out
  dtab: |
    /svc/* => /$/inet/127.1/4144;
  servers:
  - port: 4143
    ip: 0.0.0.0
  client:
    tls:
      commonName: linkerd
      disableValidation: true
      trustCerts:
      - finagle/h2/src/e2e/resources/cacert.pem
      clientAuth:
        certPath: finagle/h2/src/e2e/resources/linkerd-tls-e2e-cert.pem
        keyPath: finagle/h2/src/e2e/resources/linkerd-tls-e2e-key.pem
- protocol: h2
  experimental: true
  label: in
  dtab: |
    /svc/* => /$/inet/localhost/1234;
  servers:
  - port: 4144
    ip: 0.0.0.0
    tls:
      certPath: finagle/h2/src/e2e/resources/linkerd-tls-e2e-cert.pem
      keyPath: finagle/h2/src/e2e/resources/linkerd-tls-e2e-key.pem
      caCertPath: finagle/h2/src/e2e/resources/cacert.pem
      requireClientAuth: true
```

### output

```
D 0821 23:06:33.611 UTC THREAD317: [S L:/127.0.0.1:4143 R:/127.0.0.1:65405 S:69] initialized stream
0821 23:06:33.613 508de878e78cfd7a.508de878e78cfd7a<:508de878e78cfd7a] Message(namer.success)
WARN 0821 16:06:33.617 PDT finagle/netty4-8: Failed to initialize a channel. Closing: [id: 0x5ae1276b]
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:317)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:272)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:770)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446)
```

**Comment by siggy** [comment]
error is coming from netty's `JdkSslContext.java` because it only supports `ALPN` and `NPN`, _not_ `NPN_AND_ALPN`:
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L312

looks like finagle sets this protocol explicitly:
https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/Netty4SslConfigurations.scala#L73

**Comment by siggy** [comment]
suspect ?

https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/client/Netty4ClientEngineFactory.scala#L60

**Comment by a4chet** [comment]
I was able to get linkerd http2/tls grpc working by importing my (self-signed) certificate into my java's cacerts file like this:

`keytool -import -trustcacerts -keystore /opt/java/jre/lib/security/cacerts \
   -storepass changeit -noprompt -alias mycert -file /tmp/examplecert.crt`

and my yml config is like so:

```
routers:
- protocol: h2
  client:
    tls:
      #disableValidation: true
      commonName: localhost
      clientAuth:
        certPath: C:/dev/linkerd-1.1.3/certs/localhost.crt
        keyPath: C:/dev/linkerd-1.1.3/certs/localhost.key
  label: grpc
  experimental: true
  dtab: |
    /srv        => /#/io.l5d.fs/grpc;
    /grpc       => /srv;
    /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
  identifier:
    kind: io.l5d.header.path
    segments: 2
  servers:
  - port: 10000
    ip: 0.0.0.0
    # accept incoming TLS traffic from remote linkerd
    tls:
      certPath: C:/dev/apple/linkerd-1.1.3/certs/localhost.crt
      keyPath: C:/dev/apple/linkerd-1.1.3/certs/localhost.key
```

And now I can proxy h2/tls grpc through linkerd!

**Comment by adleong** [comment]
If I'm reading this correctly, it seems that setting `disableValidation: true` forces the use of the JDK SSL provider which does not support client auth.  Therefore, disableValidation and clientAuth and incompatible.  

@hawkw, you had the original repro of this issue.  Can you confirm that removing `disableValidation: true` makes the problem go away?

If this is the case, we should add documentation indicating that disableValidation and clientAuth are incompatible and potentially also add config validation that disallows both options from being set.

**Comment by hawkw** [comment]
@adleong Confirmed, removing `disableValidation: true` fixes this issue on the test GCE instance I set up to reproduce this. I'll add that to the documentation.
