### ISSUE TITLE
Exceptions on http retries

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1594]
Issue Type:

- [x] Bug report

**What happened**:
Occasionally when retrying failed http requests, linkerd throws exceptions:

```
D 0817 19:03:52.667 UTC THREAD34: Failed mid-stream. Terminating stream, closing connection
com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
	at com.twitter.io.Reader$$anon$1.discard(Reader.scala:234)
	at com.twitter.finagle.netty4.http.StreamTransports$$anon$1.discard(StreamTransports.scala:69)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2.discard(DelayedReleaseService.scala:56)
	at com.twitter.finagle.http.codec.HttpServerDispatcher$$anonfun$handle$2.applyOrElse(HttpServerDispatcher.scala:61)
	at com.twitter.finagle.http.codec.HttpServerDispatcher$$anonfun$handle$2.applyOrElse(HttpServerDispatcher.scala:60)
	at com.twitter.util.Promise.raise(Promise.scala:681)
	at com.twitter.util.Future$JoinPromise$$anonfun$2.applyOrElse(Future.scala:254)
	at com.twitter.util.Future$JoinPromise$$anonfun$2.applyOrElse(Future.scala:251)
	at com.twitter.util.Promise.raise(Promise.scala:681)
	at com.twitter.util.Promise.raise(Promise.scala:686)
	at com.twitter.finagle.http.exp.GenSerialServerDispatcher.$anonfun$new$1(ServerDispatcher.scala:125)
	at com.twitter.util.Future.$anonfun$ensure$1(Future.scala:941)
	at com.twitter.util.Future.$anonfun$ensure$1$adapted(Future.scala:941)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:202)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:193)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:530)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:520)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:877)
	at com.twitter.finagle.netty4.transport.ChannelTransport.com$twitter$finagle$netty4$transport$ChannelTransport$$fail(ChannelTransport.scala:95)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.exceptionCaught(ChannelTransport.scala:190)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at com.twitter.finagle.netty4.channel.ChannelExceptionHandler.exceptionCaught(ChannelExceptionHandler.scala:55)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:426)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
	at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.exceptionCaught(ChannelStatsHandler.scala:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:914)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:104)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:145)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
```
and

```
D 0817 19:03:52.666 UTC THREAD34: ChannelStatsHandler caught an exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:433)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
```

We suspect they're coming from https://github.com/linkerd/linkerd/blob/92036e4f3ea8204b84823e6a795740462e5ead25/router/core/src/main/scala/com/twitter/finagle/buoyant/RetryFilter.scala#L69

**What you expected to happen**:
It's fine to discard the current response, but the exceptions are too noisy/distracting. They should be suppressed/caught.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-cayenne-config10
data:
  config.yaml: |-
    admin:
      port: 9910
    namers:
    - kind: io.l5d.k8s.ns
      host: localhost
      port: 8001
      envVar: POD_NS

    routers:
    - protocol: http
      label: retryableIncoming
      servers:
      - port: 3310
        ip: 0.0.0.0
      dtab: /svc => /$/inet/127.1/7010;

    - protocol: http
      label: outgoing
      dtab: |
        /svc => /#/io.l5d.k8s.ns/http;
      servers:
      - port: 5310
      identifier:
        kind: io.l5d.path

    telemetry:
    - kind: io.l5d.prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-potato-config10
data:
  config.yaml: |-
    admin:
      port: 9910

    routers:
    - protocol: http
      label: incoming
      servers:
      - port: 4310
        ip: 0.0.0.0
      identifier:
        kind: io.l5d.path
        consume: true
      dtab: |
        /svc => /$/inet/127.1/7010;

    telemetry:
    - kind: io.l5d.prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cayenne10
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cayenne10
        testrun: test10
    spec:
      dnsPolicy: ClusterFirst
      volumes:
      - name: linkerd-config
        configMap:
          name: "l5d-cayenne-config10"
      containers:
      - name: retry-service
        image: gcr.io/buoyant-hosted/tools:2017-05-15-9a4dcb8
        command:
        - buoyant/bin/topgen
        - "-addr=7010"
        - "-linkerd-url=http://localhost:5310"
        - "-identifier=path"
        - "-downstreams=potato10"
        - "-rate=1.0"
        - "-failure-rate=0.5"
        ports:
        - name: service
          containerPort: 7010

      - name: l5d
        image: buoyantio/linkerd:1.1.1
        imagePullPolicy: Always
        env:
        - name: POD_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "/io.buoyant/linkerd-helium/config/config.yaml"
        - "-com.twitter.finagle.tracing.debugTrace=true"
        - "-log.level=DEBUG"
        ports:
        - name: retryable
          containerPort: 3310
        - name: outgoing
          containerPort: 5310
        - name: admin
          containerPort: 9910
        volumeMounts:
        - name: "linkerd-config"
          mountPath: "/io.buoyant/linkerd-helium/config"
          readOnly: true

      - name: kubectl
        image: buoyantio/kubectl:v1.6.2
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: cayenne10
spec:
  selector:
    app: cayenne10
  type: LoadBalancer
  ports:
  - name: retryable
    port: 3310
  - name: admin
    port: 9910
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: potato10
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: potato10
        testrun: test10
    spec:
      dnsPolicy: ClusterFirst
      volumes:
      - name: linkerd-config
        configMap:
          name: "l5d-potato-config10"
      containers:
      - name: service
        image: gcr.io/buoyant-hosted/tools:2017-05-15-9a4dcb8
        command:
        - buoyant/bin/topgen
        - "-addr=7010"
        - "-identifier=path"
        ports:
        - name: service
          containerPort: 7010

      - name: l5d
        image: buoyantio/linkerd:1.1.1
        imagePullPolicy: Always
        args:
        - "/io.buoyant/linkerd-helium/config/config.yaml"
        - "-com.twitter.finagle.tracing.debugTrace=true"
        - "-log.level=DEBUG"
        ports:
        - name: incoming
          containerPort: 4310
        - name: admin
          containerPort: 9910
        volumeMounts:
        - name: "linkerd-config"
          mountPath: "/io.buoyant/linkerd-helium/config"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: potato10
spec:
  selector:
    app: potato10
  clusterIP: None
  ports:
  - name: http
    port: 4310
  - name: admin
    port: 9910
---
kind: Job
apiVersion: batch/v1
metadata:
  name: slow-cooker-retry10
spec:
  template:
    metadata:
      name: slow-cooker-retry10
      labels:
        testrun: test10
    spec:
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.1.0
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          sleep 30 # wait for pods to start
          slow_cooker \
            -qps 200 \
            -concurrency 1 \
            -interval 30s \
            -metric-addr 0.0.0.0:9910 \
            http://cayenne10.test.svc.cluster.local:3310
        ports:
        - name: slow-cooker
          containerPort: 9910
      restartPolicy: OnFailure
```

**Comment by hawkw** [comment]
A quick update: as of 0b333dd6382954e6915b86318b862e4ab57c5de4, I've got this half-done: the `ReaderDiscarded` exception is ignored. The `IOException` is still being thrown – trying to figure out where that exception needs to be caught in order to only ignore it when it's being thrown spuriously.
