### ISSUE TITLE
io.l5d.etcd sends get requests without a Host header causing a 400 in etcd and thus a 500 in namerd

### ISSUE THREAD

**Issue by krak3n** [linkerd/linkerd#1699]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

`namerd` returns a `500` when using `etcd` as a storage backend when listing dtabs (`namerctl dtab list`).

```
Error: unexpected response: 500 Internal Server Error
Usage:
  namerctl dtab list [flags]

Aliases:
  list, ls


Global Flags:
      --base-url string   namer location (e.g. http://namerd.example.com:4080)
      --config string     config file
      --json              input/output in json instead of text

unexpected response: 500 Internal Server Error
```

Logs:

```
io.buoyant.etcd.UnexpectedResponse: GET /v2/keys/namerd/dtabs?recursive=true [(recursive -> true)] Status(400)
	at io.buoyant.etcd.NodeOp$.$anonfun$mk$4(NodeOp.scala:71)
	at com.twitter.util.Try.transform(Try.scala:222)
	at io.buoyant.etcd.NodeOp$.mk(NodeOp.scala:69)
	at io.buoyant.etcd.Key.$anonfun$get$2(Key.scala:83)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1740)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:239)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:220)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:532)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise.runq(Promise.scala:522)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:887)
	at com.twitter.util.Promise.update(Promise.scala:859)
	at com.twitter.util.Promise.setValue(Promise.scala:835)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:122)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1337)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:916)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:748)
```

**What you expected to happen**:

`namerctl` to list out dtabs.

**How to reproduce it (as minimally and precisely as possible)**:

Create an `etcd` cluster, set `namerd` to use `ectd` as a storage backend. Add some dtabs and try to retrieve them.

**Anything else we need to know?**:

After doing some debugging `ectd` is returning a `400  Bad Request`. This however not an `etcd` problem. Installing `tcpflow` on a `namerd` container we can see  that `namerd` sends a `HTTP/1.1 GET` request without a `Host` header and thus is a bad request:

```
010.056.000.031.50276-010.056.001.030.02379: GET /v2/keys/namerd/dtabs?recursive=true HTTP/1.1
Accept: application/json
X-B3-TraceId: f6277069f24295be
X-B3-SpanId: 7df74d2a46384724
X-B3-ParentSpanId: f6277069f24295be
X-B3-Sampled: false
X-B3-Flags: 0
Finagle-Ctx-com.twitter.finagle.Retries: 0


010.056.001.030.02379-010.056.000.031.50276: HTTP/1.1 400 Bad Request: missing required Host header
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request: missing required Host header
``` 

A `curl` command for the same request in the same container yields the correct response:

```
curl http://etcd.namerd:2379/v2/keys/namerd/dtabs?recursive=true
{"action":"get","node":{"key":"/namerd/dtabs","dir":true,"nodes":[...],"modifiedIndex":8,"createdIndex":8}}
```

This check was introduced in golang/go#13624 and likely released in 2016 some time. `etcd` would have started building against this version and thus this requirement was added.

**Environment**:

- linkerd: 1.3.1
``` yml
admin:
  ip: 0.0.0.0
  port: 9990
telemetry:
- kind: io.l5d.prometheus
- kind: io.l5d.recentRequests
  sampleRate: 0.25
usage:
  enabled: false
routers:
- protocol: h2
  experimental: true
  label: dev-out
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: dev-out
  servers:
  - port: 4040
    ip: 0.0.0.0
- protocol: h2
  experimental: true
  label: dev-in
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: dev-in
    transformers:
    - kind: io.l5d.k8s.localnode
  servers:
  - port: 4041
    ip: 0.0.0.0
- protocol: h2
  experimental: true
  label: qa-out
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: qa-out
  servers:
  - port: 4140
    ip: 0.0.0.0
- protocol: h2
  experimental: true
  label: qa-in
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: qa-in
    transformers:
    - kind: io.l5d.k8s.localnode
  servers:
  - port: 4141
    ip: 0.0.0.0
- protocol: h2
  experimental: true
  label: prod-out
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: prod-out
  servers:
  - port: 4240
    ip: 0.0.0.0
- protocol: h2
  experimental: true
  label: prod-in
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.namerd.svc.cluster.local/4100
    namespace: prod-in
    transformers:
    - kind: io.l5d.k8s.localnode
  servers:
  - port: 4241
    ip: 0.0.0.0
```

- namerd: 1.3.1
``` yml
admin:
  ip: 0.0.0.0
  port: 9991
namers:
- kind: io.l5d.k8s
  experimental: true
  host: localhost
  port: 8001
storage:
  kind: io.l5d.etcd
  experimental: true
  host: etcd.namerd
  port: 2379
  pathPrefix: /namerd/dtabs
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100 
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

- Kubernetes
- Google Kubernetes Engine

**Comment by krak3n** [comment]
Also see the discord thread: https://discourse.linkerd.io/t/namerd-etcd-400-bad-request-on-get-v2-keys-namerd-dtabs-recursive-true/368

**Comment by deebo91** [comment]
Thanks for all the useful info @krak3n. We are taking a look at this.
