### ISSUE TITLE
NoClassDefFoundError when using zkLeader namer

### ISSUE THREAD

**Issue by jftz** [linkerd/linkerd#1713]
Issue Type:

- [X ] Bug report
- [ ] Feature request

**What happened**:
NoClassDefFoundError when trying to use the io.l5d.zkLeader namer.
Caused by: java.lang.NoClassDefFoundError: com/twitter/common/util/BackoffHelper
	at com.twitter.common.zookeeper.Group.<init>(Group.java:99)
	at com.twitter.common.zookeeper.Group.<init>(Group.java:115)
	at com.twitter.common.zookeeper.Group.<init>(Group.java:107)
	at io.buoyant.namer.zk.ZkLeaderNamer.bind(ZkLeaderNamer.scala:38)
	at io.buoyant.namer.zk.ZkLeaderNamer.lookup(ZkLeaderNamer.scala:31)

**What you expected to happen**:
No exception.

**How to reproduce it (as minimally and precisely as possible)**:
Add a io.l5d.zkLeader name to your linkerd yaml file.
Send a request to that linkerd instance.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
linkerd-1.3.0
Ubuntu 14.04.5 LTS

**Comment by franziskagoltz** [comment]
Thank you for submitting this bug report @jftz!

**Comment by siggy** [comment]
@jftz Can please include a bit more detail? Please try this with linkerd 1.3.5+ and provide the following:
- linkerd config file
- linkerd log
- command(s) to reproduce the issue.

**Comment by adleong** [comment]
@jftz are you still seeing this issue?  Can you provide the information above so that we can help investigate?
