### ISSUE TITLE
Exception when using admin UI to inspect dtab delegations

### ISSUE THREAD

**Issue by obeattie** [linkerd/linkerd#1731]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**: When using the admin UI to perform dtab delegations, this often seems to throw an error in our environment:

```W 1206 10:20:26.907 UTC THREAD27: Exception propagated to the default monitor (upstream address: /10.224.49.0:49572, downstream address: n/a, label: adminhttp).
DelegationFailure(The maximum number of concurrent observations has been reached (10))
	at io.buoyant.namerd.iface.thriftscala.DelegationFailure$.decode(DelegationFailure.scala:122)
	at io.buoyant.namerd.iface.thriftscala.Namer$Delegate$Result$.readDfValue(Namer.scala:1397)
	at io.buoyant.namerd.iface.thriftscala.Namer$Delegate$Result$.decode(Namer.scala:1341)
	at io.buoyant.namerd.iface.thriftscala.Namer$Delegate$Result$.decode(Namer.scala:1245)
	at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.decodeResponse(Namer$FinagleClient.scala:79)
	at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.$anonfun$delegate$1(Namer$FinagleClient.scala:233)
	at com.twitter.finagle.thrift.DeserializeCtx.deserialize(DeserializeCtx.scala:38)
	at com.twitter.finagle.thriftmux.service.ThriftMuxResponseClassifier$$anon$2.deserializeIfPossible(ThriftMuxResponseClassifier.scala:167)
	at com.twitter.finagle.thriftmux.service.ThriftMuxResponseClassifier$$anon$2.isDefinedAt(ThriftMuxResponseClassifier.scala:177)
	at com.twitter.finagle.thriftmux.service.ThriftMuxResponseClassifier$$anon$2.isDefinedAt(ThriftMuxResponseClassifier.scala:155)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at com.twitter.finagle.thriftmux.service.ThriftMuxResponseClassifier$$anon$2.applyOrElse(ThriftMuxResponseClassifier.scala:155)
	at com.twitter.finagle.service.StatsFilter.$anonfun$apply$1(StatsFilter.scala:175)
	at com.twitter.finagle.service.StatsFilter.$anonfun$apply$1$adapted(StatsFilter.scala:169)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:202)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:193)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:530)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:520)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:883)
	at com.twitter.util.Promise.update(Promise.scala:857)
	at com.twitter.util.Promise.setValue(Promise.scala:833)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.codec.BufCodec$.channelRead(BufCodec.scala:66)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:42)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:748)
```

**What you expected to happen**: The delegation results should be returned.

**How to reproduce it (as minimally and precisely as possible)**: I'm not 100% sure why we're hitting this issue; there has been [some discussion in Slack about this previously](https://linkerd.slack.com/archives/C0JV5E7BR/p1507222184000355).

I'm hoping the stack trace and error message are enough to identity this, but please let me know if you do need any more info. 😄 

**Environment**:
- linkerd/namerd version, config files:
    - linkerd v1.1.3
    - namerd v1.1.3
- Platform, version, and config files (Kubernetes, DC/OS, etc):
    - Kubernetes v1.7.4
    - I can share config files privately if needed
- Cloud provider or hardware configuration:
    - AWS

**Comment by adleong** [comment]
My understanding is that the Linkerd admin UI only makes short-lived observations of delegations to Namerd.  In effect, when the Linkerd admin UI does a delegation, it should cause Linkerd to make a thrift call to `delegate` with no stamp.  When Namerd returns a response with a stamp, Linkerd will make another `delegate` call with the returned stamp but should cancel the request very quickly (because the admin UI only required the initial value).  Therefore, the number of entries in Namerd's delegation ActiveCache should be roughly equal to the number of concurrent requests to Linkerd admin UIs.

Two potential solutions:
* Size the delegate active cache to be large enough to accommodate the number of concurrent admin UI requests.
* Add a non-long-polling method to retrieve only the initial value of a delegation, instead of using a short lived observation.

**Comment by jackkleeman** [comment]
What would you prefer @adleong? The first seems simpler but it's hard to estimate how many requests we need to accommodate

**Comment by adleong** [comment]
@jackkleeman yeah, you've hit the nail on the head.  the first would be very simple but would require an estimate on the number of concurrent requests.  However, it should be safe to set this number to be quite large.  For example, the default size for the binding and addr active caches are 1000 each.

**Comment by jackkleeman** [comment]
OK, I can write a PR now setting it to 1000?

**Comment by adleong** [comment]
:+1: I think that's a good idea.

**Comment by adleong** [comment]
I believe this should be fixed by https://github.com/linkerd/linkerd/pull/1862
