### ISSUE TITLE
Namerd request to Consul "times out" if DTab stored in Consul is malformed

### ISSUE THREAD

**Issue by rclayton-the-terrible** [linkerd/linkerd#1759]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

When requesting DTabs from Consul, if Namerd has not already cached a valid DTab configuration, Namerd will stall (as if it's waiting for data from Consul) if the DTab is malformed.  The logs do not display a warning that the DTab is malformed and the Namerd Admin console hangs waiting for a response from the Namerd node.

```
E 1220 00:26:45.879 UTC THREAD27: adminhttp
com.twitter.finagle.CancelledRequestException: request cancelled. Remote Info: Not Available
```

**What you expected to happen**:

I expect an error in the Namerd logs saying it can't parse the DTab and any request via the Admin console to return that error.

**How to reproduce it (as minimally and precisely as possible)**:

1.  Create a Consul cluster.
2.  Create a Consul KV entry with an invalid DTab.
3.  Create a Namerd config that uses Consul Storage via that Consul keyspace
4.  Start Namerd.
5.  Go to Namerd Admin console.  Attempt to access the DTab.

**Anything else we need to know?**:

**Environment**:

- This has occurred since we first started using Namerd (0.9.x) and is still present in the latest version (1.3.4)
- Running everything AWS ECS, with Consul versions 0.9.3 and 1.0.2 (tried both).  However, we've experienced the same problem via Docker Compose.

Here's the Consul info (just in case):

```
/ # consul info -http-addr 10.26.8.35:8500
agent:
    check_monitors = 0
    check_ttls = 0
    checks = 4
    services = 4
build:
    prerelease = 
    revision = 112c060
    version = 0.9.3
consul:
    bootstrap = true
    known_datacenters = 1
    leader = true
    leader_addr = 10.26.8.35:8300
    server = true
raft:
    applied_index = 1479
    commit_index = 1479
    fsm_pending = 0
    last_contact = 0
    last_log_index = 1479
    last_log_term = 2
    last_snapshot_index = 0
    last_snapshot_term = 0
    latest_configuration = [{Suffrage:Voter ID:10.26.8.35:8300 Address:10.26.8.35:8300}]
    latest_configuration_index = 1
    num_peers = 0
    protocol_version = 2
    protocol_version_max = 3
    protocol_version_min = 0
    snapshot_version_max = 1
    snapshot_version_min = 0
    state = Leader
    term = 2
runtime:
    arch = amd64
    cpu_count = 2
    goroutines = 85
    max_procs = 2
    os = linux
    version = go1.9
serf_lan:
    coordinate_resets = 0
    encrypted = false
    event_queue = 0
    event_time = 2
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 2
    members = 2
    query_queue = 0
    query_time = 1
serf_wan:
    coordinate_resets = 0
    encrypted = false
    event_queue = 0
    event_time = 1
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1

/ # consul members
Node                                                         Address          Status  Type    Build  Protocol  DC                              Segment
master-1                                                     10.26.8.35:8301  alive   server  0.9.3  2         qa-feature-something-something  <all>
qa-services-feature-something-something-i-0fb6030d99d904dc9  10.26.8.67:8301  alive   client  0.9.3  2         qa-feature-something-something  <default>
```

And our Namerd configuration (keep in mind the IP's are generated at deployment time):

```
admin:
  ip: 0.0.0.0
  port: 9991
interfaces:
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180
namers:
  - kind: io.l5d.consul
    host: 10.26.8.67
    prefix: /consul
    includeTag: true
storage:
  kind: io.l5d.consul
  host: 10.26.8.67
  pathPrefix: /namerd/dtabs
```

**Comment by wmorgan** [comment]
Thanks, @rclayton-the-terrible. We'll take a look.

**Comment by hawkw** [comment]
Hi @rclayton-the-terrible  I've successfully reproduced this issue using the steps you've provided (thanks!) and can confirm that it's happening with Namerd 1.3.4. I'll look into getting it fixed.

**Comment by hawkw** [comment]
Okay, I've figured out what's going wrong here. Should have a fix ready soon! :)

**Comment by hawkw** [comment]
Hi again @rclayton-the-terrible, merging PR #1760 should improve this significantly – Namerd will now log that a dtab parsing error occurred and describe why the dtab was invalid, like
```
E 1220 20:46:06.770 UTC THREAD31 TraceId:30cbad82deebb433: consul ns consul dtab parsing failed: java.lang.IllegalArgumentException: '/' expected but 'a' found at '[a]sjgfdskjhsdfg;'; dtab: 'asjgfdskjhsdfg;'
```

I've also opened a follow-on issue #1761 to display dtab parse error messages in the web UI as well as in the logs.

**Comment by rclayton-the-terrible** [comment]
@hawkw you guys are the best!  Thank you for the quick turnaround.

**Comment by wmorgan** [comment]
@rclayton-the-terrible do you have a way of verifying #1760, e.g. by building from that branch?

**Comment by rclayton-the-terrible** [comment]
@wmorgan I will try as soon as possible to verify, but I doubt I will have time before vacation (which starts in 3 hours!).  Therefore, I won't be able to get to it until early January.  Fortunately, discovering that having an invalid DTab was causing my issue has unblocked me on my infrastructure project (so this is not such a high priority at the moment).

**Comment by hawkw** [comment]
@rclayton-the-terrible, I'm happy to build a snapshot Namerd executable or Docker image for you if it makes verifying these changes any easier...

**Comment by rclayton-the-terrible** [comment]
@hawkw if you do that, I will take the time to test tonight -- prefer Docker image.

**Comment by hawkw** [comment]
@rclayton-the-terrible, just pushed an image tagged `buoyantio/namerd:1.3.4-SNAPSHOT-consul-parse-errors` to Docker Hub.

**Comment by rclayton-the-terrible** [comment]
@hawkw OK, success:

The malformed Dtab was:

```
/virtual/qa/limesurvey => /actual/{outage};
/dns/com/intelli-zoom/feature-something-something-survey-qa => /virtual/qa/limesurvey;
/virtual/qa/gateway => /actual/outage;
/dns/com/intelli-zoom/feature-something-something => /virtual/qa/gateway;
/svc => /$/io.buoyant.http.domainToPathPfx/dns;
/actual => /#/consul/qa-feature-something-something/ecs-qa;
```

And the logs show:

```
E 1220 23:01:36.149 UTC THREAD36 TraceId:bc70c71e388327ee: consul ns ecs-qa-entrypoint dtab parsing failed: java.lang.IllegalArgumentException: label char expected but '{' found at '/virtual/qa/limesurvey => /actual/[{]outage};
/dns/com/intelli-zoom/feature-something-something-survey-qa => /virtual/qa/limesurvey;
/virtual/qa/gateway => /actual/outage;
/dns/com/intelli-zoom/feature-something-something => /virtual/qa/gateway;
/svc => /$/io.buoyant.http.domainToPathPfx/dns;
/actual => /#/consul/qa-feature-something-something/ecs-qa;'; dtab: '/virtual/qa/limesurvey => /actual/{outage};
/dns/com/intelli-zoom/feature-something-something-survey-qa => /virtual/qa/limesurvey;
/virtual/qa/gateway => /actual/outage;
/dns/com/intelli-zoom/feature-something-something => /virtual/qa/gateway;
/svc => /$/io.buoyant.http.domainToPathPfx/dns;
/actual => /#/consul/qa-feature-something-something/ecs-qa;'
E 1220 23:01:36.152 UTC THREAD36: adminhttp
java.lang.IllegalArgumentException: label char expected but '{' found at '/virtual/qa/limesurvey => /actual/[{]outage};
/dns/com/intelli-zoom/feature-something-something-survey-qa => /virtual/qa/limesurvey;
/virtual/qa/gateway => /actual/outage;
/dns/com/intelli-zoom/feature-something-something => /virtual/qa/gateway;
/svc => /$/io.buoyant.http.domainToPathPfx/dns;
/actual => /#/consul/qa-feature-something-something/ecs-qa;'
	at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:29)
	at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:36)
	at com.twitter.finagle.NameTreeParsers.parseLabel(NameTreeParsers.scala:111)
	at com.twitter.finagle.NameTreeParsers.parsePath(NameTreeParsers.scala:173)
	at com.twitter.finagle.NameTreeParsers.parseSimple(NameTreeParsers.scala:220)
	at com.twitter.finagle.NameTreeParsers.parseWeighted(NameTreeParsers.scala:250)
	at com.twitter.finagle.NameTreeParsers.parseTree1(NameTreeParsers.scala:198)
	at com.twitter.finagle.NameTreeParsers.parseTree(NameTreeParsers.scala:184)
	at com.twitter.finagle.NameTreeParsers.parseDentry(NameTreeParsers.scala:258)
	at com.twitter.finagle.NameTreeParsers.parseDtab(NameTreeParsers.scala:268)
	at com.twitter.finagle.NameTreeParsers.parseAllDtab(NameTreeParsers.scala:305)
	at com.twitter.finagle.NameTreeParsers$.parseDtab(NameTreeParsers.scala:12)
	at com.twitter.finagle.Dtab$.read(Dtab.scala:356)
	at io.buoyant.namerd.storage.consul.ConsulDtabStore.$anonfun$_observe$3(ConsulDtabStore.scala:177)
	at com.twitter.util.Try$.apply(Try.scala:15)
	at io.buoyant.namerd.storage.consul.ConsulDtabStore.$anonfun$_observe$2(ConsulDtabStore.scala:177)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:239)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:220)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:532)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise.runq(Promise.scala:522)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:887)
	at com.twitter.util.Promise.update(Promise.scala:859)
	at com.twitter.util.Promise.setValue(Promise.scala:835)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:122)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:33)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:748)

W 1220 23:01:36.153 UTC THREAD36: Exception propagated to the default monitor (upstream address: /172.16.33.17:51684, downstream address: n/a, label: adminhttp).
java.lang.IllegalArgumentException: label char expected but '{' found at '/virtual/qa/limesurvey => /actual/[{]outage};
/dns/com/intelli-zoom/feature-something-something-survey-qa => /virtual/qa/limesurvey;
/virtual/qa/gateway => /actual/outage;
/dns/com/intelli-zoom/feature-something-something => /virtual/qa/gateway;
/svc => /$/io.buoyant.http.domainToPathPfx/dns;
/actual => /#/consul/qa-feature-something-something/ecs-qa;'
	at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:29)
	at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:36)
	at com.twitter.finagle.NameTreeParsers.parseLabel(NameTreeParsers.scala:111)
	at com.twitter.finagle.NameTreeParsers.parsePath(NameTreeParsers.scala:173)
	at com.twitter.finagle.NameTreeParsers.parseSimple(NameTreeParsers.scala:220)
	at com.twitter.finagle.NameTreeParsers.parseWeighted(NameTreeParsers.scala:250)
	at com.twitter.finagle.NameTreeParsers.parseTree1(NameTreeParsers.scala:198)
	at com.twitter.finagle.NameTreeParsers.parseTree(NameTreeParsers.scala:184)
	at com.twitter.finagle.NameTreeParsers.parseDentry(NameTreeParsers.scala:258)
	at com.twitter.finagle.NameTreeParsers.parseDtab(NameTreeParsers.scala:268)
	at com.twitter.finagle.NameTreeParsers.parseAllDtab(NameTreeParsers.scala:305)
	at com.twitter.finagle.NameTreeParsers$.parseDtab(NameTreeParsers.scala:12)
	at com.twitter.finagle.Dtab$.read(Dtab.scala:356)
	at io.buoyant.namerd.storage.consul.ConsulDtabStore.$anonfun$_observe$3(ConsulDtabStore.scala:177)
	at com.twitter.util.Try$.apply(Try.scala:15)
	at io.buoyant.namerd.storage.consul.ConsulDtabStore.$anonfun$_observe$2(ConsulDtabStore.scala:177)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:239)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:220)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:532)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise.runq(Promise.scala:522)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:887)
	at com.twitter.util.Promise.update(Promise.scala:859)
	at com.twitter.util.Promise.setValue(Promise.scala:835)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:122)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:33)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:748)
```

And the UI request failed (instead of hung waiting forever):

![screenshot from 2017-12-20 15-02-14](https://user-images.githubusercontent.com/1059830/34232861-35d24ed4-e597-11e7-9cd1-0e397164e5e4.png)

**Comment by hawkw** [comment]
@rclayton-the-terrible that's great! We'll also look into making the UI present the error in a way that's a little more informative than `HTTP ERROR 500` (see #1761).
