### ISSUE TITLE
Netty NPEs during TLS handshake

### ISSUE THREAD

**Issue by jjshanks** [linkerd/linkerd#1825]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

```
W 0219 22:49:03.939 UTC THREAD25: ChannelStatsHandler caught an exception
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: ssl
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: ssl
	at io.netty.internal.tcnative.SSL.getHandshakeCount(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.rejectRemoteInitiatedRenegotiation(ReferenceCountedOpenSslEngine.java:1117)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1080)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1126)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:215)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 18 more

```

**What you expected to happen**:

No exception

**How to reproduce it (as minimally and precisely as possible)**:

Happens in our h2 router with a cert and key only

**Anything else we need to know?**:

Appears to be a bug in netty since 4.1.13. https://github.com/netty/netty/issues/7353

Fixed in 4.1.17

**Environment**:
- linkerd/namerd version, config files: 1.3.5

**Comment by wmorgan** [comment]
Adding tentatively to 1.3.6.

**Comment by pbagchi** [comment]
Literally just ran into this myself.

**Comment by wmorgan** [comment]
PRs welcome :)

**Comment by jjshanks** [comment]
Did a little poking on this and I think it will require updating finagle which doesn't seem to be doable in place without code changes.

**Comment by siggy** [comment]
Moving this out of 1.3.6. Let's do the finagle upgrade immediately after the release.

**Comment by adleong** [comment]
Unfortunately, it looks like Finagle is still on Netty 4.1.16.  We won't be able to upgrade until they do.

**Comment by adleong** [comment]
Linkerd is now on Netty 4.1.28 so this should be fixed.  Please re-open if you see this again.
