### ISSUE TITLE
short interruptions to zookeeper cause flooding of logs

### ISSUE THREAD

**Issue by Pveasey** [linkerd/linkerd#1983]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
A ~30 second interruption to Zookeeper caused Namerd to log ~hundred of thousands~ millions of lines a minute
from a single millisecond we see 26 Info level logs.  
```
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
I 0611 18:34:13.724 UTC THREAD25: Reacquiring watch on com.twitter.finagle.serverset2.client.SessionState$SyncConnected$@48731449. Session: b6341dd1df61938
```
I can share the full log but its just 500MB of the same message over a ~30 second period 

**What you expected to happen**:
Sane number of logs for connection exceptions 

**How to reproduce it (as minimally and precisely as possible)**:
Create env with Namerd using zookeeper as its backend.

stop a zookeeper service and watch the logs flood.

**Anything else we need to know?**:
In our env we run a 5 node ZK cluster and a single node disk full caused all namerd instances to restart immediately, the restart was part of the design running in Mesos a full disk results in a restart of job. 

I expect its coming from:
https://github.com/linkerd/linkerd/blob/1dd587670e9b8bbad110d87add51a3ec5b87ada4/namerd/storage/zk/src/main/scala/com/twitter/finagle/serverset2/buoyant/ZkSession.scala#L108
but i've never worked with scala before.

**Environment**:
- linkerd/namerd version, config files: namerd version namerd 1.4.0
- Platform, version, and config files (Kubernetes, DC/OS, etc): Namerd running in docker container on vanilla mesos (no DC/OS)
- Cloud provider or hardware configuration: AWS ec2 underlying hardware

**Comment by adleong** [comment]
@Pveasey can you share exactly how you interrupted Zookeeper?  I tried stopped ZK by running `zkServer.sh stop` which resulted in Namerd printing this error approximately once per second:

```
WARN 0615 16:38:27.251 PDT run-main-0-SendThread(localhost:2181): Session 0x16405c7b50d0002 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:356)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1192)
```

I was not able to get Namerd into a state where it was printing thousands or millions of logs.

**Comment by Pveasey** [comment]
@adleong a single ZK node in the cluster of 5 hit full disk. In my understanding this shouldnt cause an interruption but it caused a lot of problems for linkerd and namerd. Will try and reproduce in our dev environment, and get back to you.

**Comment by Pveasey** [comment]
@adleong I've tried to reproduce this but was unable, the only differences in config would be there are far more linkerd clients in prod (150+ vs 6). 
Id expect it is still a problem with production cluster as there was clear causation, but without hard evidence i'm good with closing.

**Comment by adleong** [comment]
@Pveasey for what it's worth, I think you're right.  Looking at the code it's totally believable that certain zookeeper responses could put Namerd into a tight retry loop.  But without the ability to repro or at least without a better understanding of what those ZK responses are, it'll be tough to fix this with any amount of confidence.  I'll close this for now but please re-open it if you get more information.
