### ISSUE TITLE
k8s reader discarded errors in linkerd 1.4.3

### ISSUE THREAD

**Issue by MikeRoetgers** [linkerd/linkerd#2012]
## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

I'm seeing a number of `com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded` exceptions in the log. While researching it I came across https://github.com/linkerd/linkerd/pull/1901 which should fix this IMO. 

```
W 0620 11:40:06.134 UTC THREAD15 TraceId:5645adf4766fc4e8: Exception propagated to the default monitor (upstream address: /10.48.2.40:34292, downstream address: localhost/127.0.0.1:8001, label: client).
com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
	at com.twitter.finagle.netty4.http.StreamTransports$$anon$1.discard(StreamTransports.scala:71)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at io.buoyant.k8s.Watchable.$anonfun$watch$5(Watchable.scala:133)
[...]

W 0620 11:40:06.207 UTC THREAD15: retrying k8s request to /api/v1/namespaces/**redacted**/endpoints/**redacted**-service on error com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
W 0620 11:40:06.222 UTC THREAD15 TraceId:b5ef9e496b842efe: Exception propagated to the default monitor (upstream address: /10.48.2.40:34292, downstream address: localhost/127.0.0.1:8001, label: client).
com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
	at com.twitter.finagle.netty4.http.StreamTransports$$anon$1.discard(StreamTransports.scala:71)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at com.twitter.finagle.http.DelayedReleaseService$$anon$2$$anon$3.discard(DelayedReleaseService.scala:58)
	at io.buoyant.k8s.Watchable.$anonfun$watch$5(Watchable.scala:133)
[...]
```

**What you expected to happen**:
Not seeing the stack traces.

**How to reproduce it (as minimally and precisely as possible)**:
Set up Linkerd in k8s with a config that uses k8s to get endpoints and watch the linkerd logs for the message

**Anything else we need to know?**:

**Environment**:
linkerd 1.4.3

**Comment by MikeRoetgers** [comment]
Whoops, my bad. Mixed up the targets in centralized logging. The exceptions were coming from a linkerd runnig version 1.3.7, the 1.4.3 instances are indeed not logging this anymore. All good.
