### ISSUE TITLE
serversets namer deadlocks

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#2129]
Originally reported by @peterfroehlich here: https://github.com/linkerd/linkerd/issues/2121#issuecomment-423450143

Full stack trades of the deadlock are in the original comment.  This appears to be a deadlock where a Zookeeper Addr Var is created in the body of a flatMap of another Zookeeper Addr Var.  This can cause (perhaps when both Vars are updated simultaneously from separate threads?) one thread to hold the lock on the ZK resolver and the other thread to hold the lock on the Var.

```
DEADLOCKS:

"finagle/netty4-1-EventThread" Id=52 BLOCKED on com.twitter.finagle.serverset2.Zk2Resolver@1fc72d68 owned by "finagle/netty4-1-EventThread" Id=28
	at com.twitter.finagle.serverset2.Zk2Resolver.$anonfun$addrOf_$9(Zk2Resolver.scala:225)
	-  blocked on com.twitter.finagle.serverset2.Zk2Resolver@1fc72d68
	at com.twitter.finagle.serverset2.Zk2Resolver.$anonfun$addrOf_$9$adapted(Zk2Resolver.scala:213)
	at com.twitter.finagle.serverset2.Zk2Resolver$$Lambda$834/781748775.apply(Unknown Source)
	at com.twitter.util.Witness$$anon$17.notify(Event.scala:454)
	at com.twitter.util.Event$$anon$8.$anonfun$register$13(Event.scala:220)
	at com.twitter.util.Event$$anon$8.$anonfun$register$13$adapted(Event.scala:211)
	at com.twitter.util.Event$$anon$8$$Lambda$847/1705443860.apply(Unknown Source)
	at com.twitter.util.Function$.$anonfun$synchronizeWith$1(Function.scala:41)
	-  locked java.lang.Object@5b5c78e7
	...



"finagle/netty4-1-EventThread" Id=28 BLOCKED on com.twitter.util.Var$$anon$4@7bbdbc52 owned by "finagle/netty4-7" Id=45
	at com.twitter.util.Var$$anon$4.observe(Var.scala:409)
	-  blocked on com.twitter.util.Var$$anon$4@7bbdbc52
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1(Var.scala:80)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1$adapted(Var.scala:68)
	...



"finagle/netty4-7" Id=45 BLOCKED on com.twitter.finagle.serverset2.Zk2Resolver@1fc72d68 owned by "finagle/netty4-1-EventThread" Id=28
	at com.twitter.finagle.serverset2.Zk2Resolver.$anonfun$addrOf_$9(Zk2Resolver.scala:225)
	-  blocked on com.twitter.finagle.serverset2.Zk2Resolver@1fc72d68
	at com.twitter.finagle.serverset2.Zk2Resolver.$anonfun$addrOf_$9$adapted(Zk2Resolver.scala:213)
	at com.twitter.finagle.serverset2.Zk2Resolver$$Lambda$834/781748775.apply(Unknown Source)
	at com.twitter.util.Witness$$anon$17.notify(Event.scala:454)
	at com.twitter.util.Event$$anon$8.$anonfun$register$13(Event.scala:217)
	at com.twitter.util.Event$$anon$8.$anonfun$register$13$adapted(Event.scala:211)
	at com.twitter.util.Event$$anon$8$$Lambda$847/1705443860.apply(Unknown Source)
	at com.twitter.util.Function$.$anonfun$synchronizeWith$1(Function.scala:41)
	-  locked java.lang.Object@6dbffb33
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@2e05833c

```

**Comment by adleong** [comment]
It looks like this is due to a bug in `finagle-serversets` which was fixed recently: https://github.com/twitter/finagle/commit/78c17dc93339dd99fd2439de60ef1009a1ace722

Linkerd will pick up this fix when we upgrade our Finagle dependency (in progress) and should be included in the next Linkerd release.
