### ISSUE TITLE
OutOfDirectMemoryError

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#2132]
Issue Type: Bug

We appear to be experiencing a direct memory leak in linkerd. We were observing `OutOfDirectMemory` errors quite frequently (almost daily) for a while and then we tuned the `-XX:MaxDirectMemory` JVM flag to increase the limit because we suspected that the value was too low to support the amount of I/O linkerd was doing. However, it only appears to have made the problem less frequent. Restarting linkerd corrects the issue for a while.

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1048576 byte(s) of direct memory (used: 535822630, max: 536870912)
 at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
 at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
 at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
 at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
 at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
 at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
 at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
 at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
 at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
 at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
 at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
 at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
 at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:71)
 at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:786)
 at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:412)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
```

The error message associated with the stack trace varies based on which allocation fails, but here are 3 recent examples: 

```
W 0929 13:30:31.280 CDT THREAD96: ChannelStatsHandler caught an exception
WARN 0929 13:30:31.282 CDT finagle/netty4-23: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
W 0929 13:30:31.282 CDT THREAD114: Unhandled exception in connection with x.x.x.56/x.x.x.56:443, shutting down connection
```

I'm going to try running a load test against linkerd with netty leak detection enabled and see if that can shed some more light on the problem. I'll report back on this issue with the results.

**Comment by adleong** [comment]
We've been able to reproduce a direct memory leak with a similar stack trace using strest-grpc.  I'm not sure if this is the same issue that you're hitting here but I'll share what I've found in case it applies to you as well.

I turned on Netty's leak detection but I kept getting the OutOfDirectMemory error without triggering any of Netty's leak detection.  This suggests to me that it was not an issue with reference counting of the direct ByteBufs but rather a "true" memory leak.  In other words, direct ByteBufs were being created and active references to them were sticking around.  I looked at Linkerd's `stream/open_streams` metrics and saw this number was very large.  This suggests a stream leak is holding references to direct ByteBufs.

I added `maxConcurrentStreamsPerConnection: 1000` to the server section in my Linkerd config and this seemed to fix the problem: I was no longer able to trigger the  OutOfDirectMemory error.

I recommend monitoring the `stream/open_streams` metrics during your testing.  If you see this number growing over time, you're probably hitting this same issue.  You can also try setting maxConcurrentStreamsPerConnection to see if that fixes the issue.

Next steps for me are to investigate the cause of the stream leak.  I also want to consider adding a default value for maxConcurrentStreamsPerConnection.

**Comment by adleong** [comment]
In our case, the stream leak was caused by an aberrant client behavior where the client was leaving streams open forever.  So technically, Linkerd was behaving correctly, although a default limit on `maxConcurrentStreamsPerConnection` would protect against this.

I'm curious to know if your situation is at all similar.  Is it possible that you have clients which are leaving streams open?

**Comment by siggy** [comment]
For reference, confirming that when `maxConcurrentStreamsPerConnection` is hit, Linkerd sends a `RST_STREAM` back to the client, with `REFUSED_STREAM` error.

From `strest-grpc`:
```
ERRO[0056] stream.Recv() returned rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM
```

<img width="1327" alt="screen shot 2018-10-09 at 4 51 11 pm" src="https://user-images.githubusercontent.com/236915/46705251-8ab60700-cbe3-11e8-87bb-a8f8e6e66d97.png">

**Comment by adleong** [comment]
hey @zackangelo!  any update on if setting `maxConcurrentStreamsPerConnection` helped this?

**Comment by adleong** [comment]
any update on this, @zackangelo?
