### ISSUE TITLE
NoClassDefFoundError: com/twitter/common/util/BackoffHelper

### ISSUE THREAD

**Issue by chenhaibocode** [linkerd/linkerd#2190]
error msg:

W 1211 16:40:30.255 CST THREAD16 TraceId:fbab9e62080cb231: Exception propagated to the default monitor (upstream address: /127.0.0.1:33758, downstream address: n/a, label: thrift).
java.lang.NoClassDefFoundError: com/twitter/common/util/BackoffHelper
	at com.twitter.common.zookeeper.Group.<init>(Group.java:99)
	at com.twitter.common.zookeeper.Group.<init>(Group.java:115)
	at com.twitter.common.zookeeper.Group.<init>(Group.java:107)
	at io.buoyant.namer.zk.ZkLeaderNamer.bind(ZkLeaderNamer.scala:38)
	at io.buoyant.namer.zk.ZkLeaderNamer.lookup(ZkLeaderNamer.scala:31)
	at io.buoyant.namer.ConfiguredDtabNamer.lookup(ConfiguredDtabNamer.scala:36)
	at io.buoyant.namer.ConfiguredDtabNamer.lookup(ConfiguredDtabNamer.scala:22)
	at io.buoyant.namer.ConfiguredDtabNamer.$anonfun$bind$2(ConfiguredDtabNamer.scala:17)
	at com.twitter.finagle.Namer$.bind(Namer.scala:223)
	at com.twitter.finagle.Namer$.$anonfun$bind$3(Namer.scala:223)
	at com.twitter.util.Activity.$anonfun$flatMap$1(Activity.scala:66)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1(Var.scala:80)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1$adapted(Var.scala:68)
	at com.twitter.util.Var$Observer.publish(Var.scala:156)
	at com.twitter.util.Var$Value.observe(Var.scala:232)
	at com.twitter.util.Var$$anon$2.observe(Var.scala:68)
	at com.twitter.util.Var.observe(Var.scala:36)
	at com.twitter.util.Var.observe$(Var.scala:36)

**Comment by chenhaibocode** [comment]
![image](https://user-images.githubusercontent.com/41729597/49788829-57b7fd00-fd65-11e8-819b-8165a699d378.png)

**Comment by chenhaibocode** [comment]
![image](https://user-images.githubusercontent.com/41729597/49788858-6c949080-fd65-11e8-9465-09b44db3044a.png)

**Comment by chenhaibocode** [comment]
![image](https://user-images.githubusercontent.com/41729597/49788914-9352c700-fd65-11e8-9b9f-4f72a44d0eb6.png)

**Comment by adleong** [comment]
Hi @chenhaibocode, this looks like it might be a problem with the way the Linkerd binary was built.  Did you build the executable yourself or download it from the releases page?  Which version?  Can you provide steps to reproduce?

**Comment by adleong** [comment]
I think this may be the same issue as #2199

**Comment by kleimkuhler** [comment]
Hi @chenhaibocode - We closed #2199 with #2208 recently.

It has been difficult to reproduce this specific issue. If this is still an issue for you, could you try reproducing it with the new `1.6.0-SNAPSHOT` binaries found in [this](https://drive.google.com/drive/folders/1plDeENjBx-eo67CF3L5n1ziVdA6pjXLi?usp=sharing) Google Drive folder? Apologies for providing the binaries this way; we have not released and uploaded the new version yet.

If that fixes the issue - great. If it does not, we ask that you try and provide some more concrete steps to reproducing this specific issue. If it requires certain configurations, please also try and provide those as text instead of images. The ability to copy and paste makes the process a lot quicker!
