### ISSUE TITLE
io.l5d.consul.interpreter ChannelException error

### ISSUE THREAD

**Issue by halfpastjohn** [linkerd/linkerd#2260]
Issue Type:

- [x ] Bug report
- [ ] Feature request

**What happened**:

I'm trying to use the io.l5d.consul.interpreter with linkerd 1.6.2 locally and in ECS. I'm receiving the below errors in both tests. I've tried many variations with host/bridge network modes, a local consul container and a remote EC2 consul instance (which it what I prefer to use). I've also tried to mimic the test performed on the PR for the feature itself, here: https://gitlab.cncf.ci/linkerd/linkerd/commit/b38a9a0f60fb9f92a49a0f17672928b6b02b5b77

The third error below is the primary one, I think. I'm always getting a ChannelClosedException finagle error when it's trying to hit either localhost or the IP of the bridge network gateway that linkerd resides on.

Additionally (and because I am unsure) I tried without namerd and used namers in my linkerd config. Same results.

```
HTTP/1.1 502 Bad Gateway
l5d-err: Unable+to+route+request%21%0A%0Aservice+name%3A+%2Fsvc%2Fasset-sor%0Aresolutions+considered%3A%0A++%2F%23%2Fio.l5d.consul%2Fus-west-2-staging%2Fasset-sor+%28neg%29%0Adtab%3A%0A++%2Fsvc+%3D%3E+%2F%23%2Fio.l5d.consul%2Fus-west-2-staging%0Abase+dtab%3A%0A%0Aoverride+dtab%3A%0A%0A
Content-Length: 211
Content-Type: text/plain

Unable to route request!

service name: /svc/asset-sor
resolutions considered:
  /#/io.l5d.consul/us-west-2-staging/asset-sor (neg)
dtab:
  /svc => /#/io.l5d.consul/us-west-2-staging
base dtab:

override dtab:
```

```
D 0327 18:23:56.290 UTC THREAD21 TraceId:566879607e78a457: consul datacenter 'us-west-2-staging' service 'asset-sor' observation error Failure(syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:8500 at remote address: localhost/127.0.0.1:8500. Remote Info: Not Available, flags=0x18) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: localhost/127.0.0.1:8500, Downstream label: client, Trace Id: 960217cbeffb62d8.960217cbeffb62d8<:960217cbeffb62d8 with Service -> client. Current state is Neg
```

```
D 0327 18:35:07.472 UTC THREAD35: closing <function1> due to read error
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /172.17.0.1:58122. Remote Info: Not Available
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelInactive(ChannelTransport.scala:175)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

metrics.json
```
{
  "jvm/start_time": 1553726310000,
  "jvm/application_time_millis": 305519.22,
  "jvm/classes/total_loaded": 8824,
  "jvm/classes/current_loaded": 8807,
  "jvm/classes/total_unloaded": 17,
  "jvm/postGC/Par_Survivor_Space/used": 292464,
  "jvm/postGC/CMS_Old_Gen/used": 18685048,
  "jvm/postGC/Par_Eden_Space/used": 0,
  "jvm/postGC/used": 18977512,
  "jvm/compiler/graal": 0,
  "jvm/nonheap/committed": 66125824,
  "jvm/nonheap/max": -1,
  "jvm/nonheap/used": 60865824,
  "jvm/tenuring_threshold": 6,
  "jvm/thread/daemon_count": 141,
  "jvm/thread/count": 142,
  "jvm/thread/peak_count": 142,
  "jvm/mem/postGC/Par_Survivor_Space/used": 292464,
  "jvm/mem/postGC/CMS_Old_Gen/used": 18685048,
  "jvm/mem/postGC/Par_Eden_Space/used": 0,
  "jvm/mem/postGC/used": 18977512,
  "jvm/mem/metaspace/max_capacity": 1107296260,
  "jvm/mem/buffer/direct/max": 671744,
  "jvm/mem/buffer/direct/count": 18,
  "jvm/mem/buffer/direct/used": 671745,
  "jvm/mem/buffer/mapped/max": 0,
  "jvm/mem/buffer/mapped/count": 0,
  "jvm/mem/buffer/mapped/used": 0,
  "jvm/mem/allocations/eden/bytes": 307747872,
  "jvm/mem/current/used": 83296224,
  "jvm/mem/current/CMS_Old_Gen/max": 724828160,
  "jvm/mem/current/CMS_Old_Gen/used": 18714584,
  "jvm/mem/current/Metaspace/max": -1,
  "jvm/mem/current/Metaspace/used": 50070888,
  "jvm/mem/current/Par_Eden_Space/max": 279183360,
  "jvm/mem/current/Par_Eden_Space/used": 3423352,
  "jvm/mem/current/Par_Survivor_Space/max": 34865152,
  "jvm/mem/current/Par_Survivor_Space/used": 292464,
  "jvm/mem/current/Compressed_Class_Space/max": 1073741820,
  "jvm/mem/current/Compressed_Class_Space/used": 8189496,
  "jvm/mem/current/Code_Cache/max": 50331648,
  "jvm/mem/current/Code_Cache/used": 2605440,
  "jvm/num_cpus": 4,
  "jvm/gc/msec": 324,
  "jvm/gc/eden/pause_msec.count": 16,
  "jvm/gc/eden/pause_msec.max": 4,
  "jvm/gc/eden/pause_msec.min": 1,
  "jvm/gc/eden/pause_msec.p50": 2,
  "jvm/gc/eden/pause_msec.p90": 3,
  "jvm/gc/eden/pause_msec.p95": 3,
  "jvm/gc/eden/pause_msec.p99": 4,
  "jvm/gc/eden/pause_msec.p9990": 4,
  "jvm/gc/eden/pause_msec.p9999": 4,
  "jvm/gc/eden/pause_msec.sum": 37,
  "jvm/gc/eden/pause_msec.avg": 2.3125,
  "jvm/gc/ParNew/msec": 223,
  "jvm/gc/ParNew/cycles": 62,
  "jvm/gc/ConcurrentMarkSweep/msec": 101,
  "jvm/gc/ConcurrentMarkSweep/cycles": 7,
  "jvm/gc/cycles": 69,
  "jvm/fd_limit": 1048576,
  "jvm/compilation/time_msec": 5434,
  "jvm/uptime": 309641,
  "jvm/safepoint/sync_time_millis": 325,
  "jvm/safepoint/total_time_millis": 727,
  "jvm/safepoint/count": 571,
  "jvm/heap/committed": 41168896,
  "jvm/heap/max": 1038876670,
  "jvm/heap/used": 22430400,
  "jvm/fd_count": 74,
  "adminhttp/sent_bytes": 965153,
  "adminhttp/connection_received_bytes.count": 3,
  "adminhttp/connection_received_bytes.max": 10393,
  "adminhttp/connection_received_bytes.min": 0,
  "adminhttp/connection_received_bytes.p50": 2879,
  "adminhttp/connection_received_bytes.p90": 10393,
  "adminhttp/connection_received_bytes.p95": 10393,
  "adminhttp/connection_received_bytes.p99": 10393,
  "adminhttp/connection_received_bytes.p9990": 10393,
  "adminhttp/connection_received_bytes.p9999": 10393,
  "adminhttp/connection_received_bytes.sum": 13256,
  "adminhttp/connection_received_bytes.avg": 4418.666666666667,
  "adminhttp/connection_duration.count": 3,
  "adminhttp/connection_duration.max": 23973,
  "adminhttp/connection_duration.min": 983,
  "adminhttp/connection_duration.p50": 8349,
  "adminhttp/connection_duration.p90": 23973,
  "adminhttp/connection_duration.p95": 23973,
  "adminhttp/connection_duration.p99": 23973,
  "adminhttp/connection_duration.p9990": 23973,
  "adminhttp/connection_duration.p9999": 23973,
  "adminhttp/connection_duration.sum": 33315,
  "adminhttp/connection_duration.avg": 11105,
  "adminhttp/connects": 16,
  "adminhttp/success": 234,
  "adminhttp/request_latency_ms.count": 138,
  "adminhttp/request_latency_ms.max": 195,
  "adminhttp/request_latency_ms.min": 0,
  "adminhttp/request_latency_ms.p50": 5,
  "adminhttp/request_latency_ms.p90": 18,
  "adminhttp/request_latency_ms.p95": 24,
  "adminhttp/request_latency_ms.p99": 79,
  "adminhttp/request_latency_ms.p9990": 195,
  "adminhttp/request_latency_ms.p9999": 195,
  "adminhttp/request_latency_ms.sum": 1347,
  "adminhttp/request_latency_ms.avg": 9.76086956521739,
  "adminhttp/admission_control/deadline/exceeded": 0,
  "adminhttp/admission_control/deadline/rejected": 0,
  "adminhttp/admission_control/deadline/expired_ms.count": 0,
  "adminhttp/received_bytes": 84609,
  "adminhttp/read_timeout": 0,
  "adminhttp/write_timeout": 0,
  "adminhttp/tcp_retransmits": 0,
  "adminhttp/connection_sent_bytes.count": 3,
  "adminhttp/connection_sent_bytes.max": 77561,
  "adminhttp/connection_sent_bytes.min": 0,
  "adminhttp/connection_sent_bytes.p50": 16923,
  "adminhttp/connection_sent_bytes.p90": 77561,
  "adminhttp/connection_sent_bytes.p95": 77561,
  "adminhttp/connection_sent_bytes.p99": 77561,
  "adminhttp/connection_sent_bytes.p9990": 77561,
  "adminhttp/connection_sent_bytes.p9999": 77561,
  "adminhttp/connection_sent_bytes.sum": 94785,
  "adminhttp/connection_sent_bytes.avg": 31595,
  "adminhttp/connection_requests.count": 3,
  "adminhttp/connection_requests.max": 28,
  "adminhttp/connection_requests.min": 0,
  "adminhttp/connection_requests.p50": 8,
  "adminhttp/connection_requests.p90": 28,
  "adminhttp/connection_requests.p95": 28,
  "adminhttp/connection_requests.p99": 28,
  "adminhttp/connection_requests.p9990": 28,
  "adminhttp/connection_requests.p9999": 28,
  "adminhttp/connection_requests.sum": 36,
  "adminhttp/connection_requests.avg": 12,
  "adminhttp/nacks": 0,
  "adminhttp/thread_usage/requests/per_thread/admin-1": 97,
  "adminhttp/thread_usage/requests/per_thread/admin-2": 138,
  "adminhttp/thread_usage/requests/mean": 67.5,
  "adminhttp/thread_usage/requests/relative_stddev": 0.17037037,
  "adminhttp/thread_usage/requests/stddev": 11.5,
  "adminhttp/transit_latency_ms.count": 0,
  "adminhttp/tls/connections": 0,
  "adminhttp/tcp_send_window_size.count": 10,
  "adminhttp/tcp_send_window_size.max": 23268,
  "adminhttp/tcp_send_window_size.min": 14432,
  "adminhttp/tcp_send_window_size.p50": 14432,
  "adminhttp/tcp_send_window_size.p90": 14432,
  "adminhttp/tcp_send_window_size.p95": 23268,
  "adminhttp/tcp_send_window_size.p99": 23268,
  "adminhttp/tcp_send_window_size.p9990": 23268,
  "adminhttp/tcp_send_window_size.p9999": 23268,
  "adminhttp/tcp_send_window_size.sum": 153488,
  "adminhttp/tcp_send_window_size.avg": 15348.8,
  "adminhttp/socket_unwritable_ms": 42,
  "adminhttp/closes": 0,
  "adminhttp/request_payload_bytes.count": 138,
  "adminhttp/request_payload_bytes.max": 0,
  "adminhttp/request_payload_bytes.min": 0,
  "adminhttp/request_payload_bytes.p50": 0,
  "adminhttp/request_payload_bytes.p90": 0,
  "adminhttp/request_payload_bytes.p95": 0,
  "adminhttp/request_payload_bytes.p99": 0,
  "adminhttp/request_payload_bytes.p9990": 0,
  "adminhttp/request_payload_bytes.p9999": 0,
  "adminhttp/request_payload_bytes.sum": 0,
  "adminhttp/request_payload_bytes.avg": 0,
  "adminhttp/nonretryable_nacks": 0,
  "adminhttp/socket_writable_ms": 32729,
  "adminhttp/response_payload_bytes.count": 138,
  "adminhttp/response_payload_bytes.max": 100461,
  "adminhttp/response_payload_bytes.min": 349,
  "adminhttp/response_payload_bytes.p50": 4245,
  "adminhttp/response_payload_bytes.p90": 58701,
  "adminhttp/response_payload_bytes.p95": 86532,
  "adminhttp/response_payload_bytes.p99": 100461,
  "adminhttp/response_payload_bytes.p9990": 100461,
  "adminhttp/response_payload_bytes.p9999": 100461,
  "adminhttp/response_payload_bytes.sum": 1942020,
  "adminhttp/response_payload_bytes.avg": 14072.608695652174,
  "adminhttp/dtab/size.count": 0,
  "adminhttp/requests": 234,
  "adminhttp/pending": 1,
  "adminhttp/handletime_us.count": 138,
  "adminhttp/handletime_us.max": 191816,
  "adminhttp/handletime_us.min": 983,
  "adminhttp/handletime_us.p50": 4688,
  "adminhttp/handletime_us.p90": 16589,
  "adminhttp/handletime_us.p95": 20242,
  "adminhttp/handletime_us.p99": 76032,
  "adminhttp/handletime_us.p9990": 191816,
  "adminhttp/handletime_us.p9999": 191816,
  "adminhttp/handletime_us.sum": 1193258,
  "adminhttp/handletime_us.avg": 8646.797101449276,
  "adminhttp/connections": 6,
  "rt/outgoing/server/0.0.0.0/4140/sent_bytes": 1264,
  "rt/outgoing/server/0.0.0.0/4140/connection_received_bytes.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/connection_duration.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/connects": 2,
  "rt/outgoing/server/0.0.0.0/4140/success": 0,
  "rt/outgoing/server/0.0.0.0/4140/request_latency_ms.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/admission_control/deadline/exceeded": 0,
  "rt/outgoing/server/0.0.0.0/4140/admission_control/deadline/rejected": 0,
  "rt/outgoing/server/0.0.0.0/4140/admission_control/deadline/expired_ms.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/received_bytes": 198,
  "rt/outgoing/server/0.0.0.0/4140/read_timeout": 0,
  "rt/outgoing/server/0.0.0.0/4140/write_timeout": 0,
  "rt/outgoing/server/0.0.0.0/4140/tcp_retransmits": 0,
  "rt/outgoing/server/0.0.0.0/4140/connection_sent_bytes.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/connection_requests.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/nacks": 0,
  "rt/outgoing/server/0.0.0.0/4140/thread_usage/requests/per_thread/finagle/netty4-1-4": 1,
  "rt/outgoing/server/0.0.0.0/4140/thread_usage/requests/per_thread/finagle/netty4-1-5": 1,
  "rt/outgoing/server/0.0.0.0/4140/thread_usage/requests/mean": 0,
  "rt/outgoing/server/0.0.0.0/4140/thread_usage/requests/relative_stddev": 0,
  "rt/outgoing/server/0.0.0.0/4140/thread_usage/requests/stddev": 0,
  "rt/outgoing/server/0.0.0.0/4140/transit_latency_ms.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/tls/connections": 0,
  "rt/outgoing/server/0.0.0.0/4140/tcp_send_window_size.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/socket_unwritable_ms": 0,
  "rt/outgoing/server/0.0.0.0/4140/closes": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/1XX": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/4XX": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/2XX": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/error": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/3XX": 0,
  "rt/outgoing/server/0.0.0.0/4140/status/5XX": 2,
  "rt/outgoing/server/0.0.0.0/4140/status/502": 2,
  "rt/outgoing/server/0.0.0.0/4140/failures": 2,
  "rt/outgoing/server/0.0.0.0/4140/failures/com.twitter.finagle.service.ResponseClassificationSyntheticException": 2,
  "rt/outgoing/server/0.0.0.0/4140/time/1XX.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/time/4XX.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/time/2XX.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/time/error.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/time/3XX.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/time/5XX.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/nonretryable_nacks": 0,
  "rt/outgoing/server/0.0.0.0/4140/socket_writable_ms": 0,
  "rt/outgoing/server/0.0.0.0/4140/dtab/size.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/requests": 2,
  "rt/outgoing/server/0.0.0.0/4140/pending": 0,
  "rt/outgoing/server/0.0.0.0/4140/handletime_us.count": 0,
  "rt/outgoing/server/0.0.0.0/4140/connections": 0,
  "rt/outgoing/service/svc/asset-sor/success": 0,
  "rt/outgoing/service/svc/asset-sor/request_latency_ms.count": 0,
  "rt/outgoing/service/svc/asset-sor/retries/per_request.count": 0,
  "rt/outgoing/service/svc/asset-sor/retries/total": 0,
  "rt/outgoing/service/svc/asset-sor/retries/budget_exhausted": 0,
  "rt/outgoing/service/svc/asset-sor/retries/budget": 100,
  "rt/outgoing/service/svc/asset-sor/failures": 2,
  "rt/outgoing/service/svc/asset-sor/failures/com.twitter.finagle.naming.buoyant.RichNoBrokersAvailableException": 2,
  "rt/outgoing/service/svc/asset-sor/requests": 2,
  "rt/outgoing/service/svc/asset-sor/pending": 0,
  "rt/outgoing/bindcache/path/expires": 0,
  "rt/outgoing/bindcache/path/evicts": 0,
  "rt/outgoing/bindcache/path/misses": 1,
  "rt/outgoing/bindcache/path/oneshots": 0,
  "rt/outgoing/bindcache/bound/expires": 0,
  "rt/outgoing/bindcache/bound/evicts": 0,
  "rt/outgoing/bindcache/bound/misses": 0,
  "rt/outgoing/bindcache/bound/oneshots": 0,
  "rt/outgoing/bindcache/tree/expires": 0,
  "rt/outgoing/bindcache/tree/evicts": 0,
  "rt/outgoing/bindcache/tree/misses": 1,
  "rt/outgoing/bindcache/tree/oneshots": 0,
  "rt/outgoing/bindcache/client/expires": 0,
  "rt/outgoing/bindcache/client/evicts": 0,
  "rt/outgoing/bindcache/client/misses": 0,
  "rt/outgoing/bindcache/client/oneshots": 0
}
```

**Environment**:
- linkerd/namerd version, config files:

linkerd.yml

```
admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  label: outgoing
  servers:
  - ip: 0.0.0.0
    port: 4140
  identifier:
   kind: io.l5d.path
   segments: 1
   consume: true
  interpreter:
    kind: io.l5d.consul.interpreter
    host: 10.20.29.200
    token: XXX-XXX-XXX
    datacenter: us-west-2-staging
```

namerd.yml

```
admin:
  ip: 0.0.0.0
  port: 9991

namers:
- kind: io.l5d.consul
  host: 10.20.29.200
  token: XXX-XXX-XXX

interfaces:
  - kind: io.l5d.httpController

storage:
  kind: io.l5d.consul
  host: 10.20.29.200
  token: XXX-XXX-XXX
  datacenter: us-west-2-staging
```

**Comment by dadjeibaah** [comment]
@halfpastjohn thanks for filing this issue, are you able to curl Consul from within the Linkerd process? Do you still get a "connection refused" message?

**Comment by dadjeibaah** [comment]
@halfpastjohn, I wanted to check in and see if you are still running into issues. For the Linkerd config you provided:
- what happens if you specify a port for the `io.l5d.consul.interpreter` config section. Do things start to work?
- Are you using both Namerd and the consul interpreter together with Linkerd?

**Comment by halfpastjohn** [comment]
@dadjeibaah I managed to get it to work however I'm not exactly certain what the fix was. I will close the ticket.

**Comment by dadjeibaah** [comment]
@halfpastjohn , Glad you got things working! If the issue comes up again please feel free to open up the ticket with additional details.
