### ISSUE TITLE
gRPC interop issue: unimplemented_method fails with INTERNAL

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#928]
While testing the interop clients against a grpc-finagle service, I've found a small interop issue

```
/Users/stevej/grpc-interop-testing-1.1.0-SNAPSHOT/bin% ./test-client --use_tls=false --server_port=60001 --test_case=unimplemented_method
Jan 13, 2017 11:29:57 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [io.grpc.internal.ManagedChannelImpl-1] Created with target directaddress:///localhost/127.0.0.1:60001
Running test unimplemented_method
Exception in thread "main" java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<INTERNAL>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.grpc.testing.integration.AbstractInteropTest.unimplementedMethod(AbstractInteropTest.java:981)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:277)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:200)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:84)
Shutting down```

**Comment by olix0r** [comment]
Fixed https://github.com/linkerd/linkerd/commit/caeae411af761b981563d356838aa1753ec6e99d
